INSERT INTO Course VALUES ('Introduction to African Studies', 'AAAS 103');
INSERT INTO Course VALUES ('European Colonial Encounter', 'AAAS 212');
INSERT INTO Course VALUES ('Race, Genomics, and Society', 'AAAS 261/CULANTH 261');
INSERT INTO Course VALUES ('Black Dance', 'AAAS 320');
INSERT INTO Course VALUES ('Race Relations in the US and South Africa', 'AAAS 390S');
INSERT INTO Course VALUES ('Chinese Lit/Cul in Translation', 'AMES 132S');
INSERT INTO Course VALUES ('Audiovisual Cultures', 'AMES 141S');
INSERT INTO Course VALUES ('Religion and Culture in Korea', 'AMES 176S');
INSERT INTO Course VALUES ('Migration and Human Rights', 'AMES 178S');
INSERT INTO Course VALUES ('China Dream', 'AMES 183');
INSERT INTO Course VALUES ('Global China', 'AMES 190S');
INSERT INTO Course VALUES ('From al-Qaeda to ISIS', 'AMES 220S');
INSERT INTO Course VALUES ('Music in South Asia', 'AMES 254');
INSERT INTO Course VALUES ('The Emergence of Modern Japan', 'AMES 269/HISTORY 227');
INSERT INTO Course VALUES ('Religion and Politics', 'AMES 288S');
INSERT INTO Course VALUES ('Breakdancers, Vocaloids and Gamers', 'AMES 316S');
INSERT INTO Course VALUES ('Chinatowns: A Cultural History', 'AMES 335');
INSERT INTO Course VALUES ('Anime: Forms and Mutation', 'AMES 361');
INSERT INTO Course VALUES ('Serial Fictions', 'AMES 390S');
INSERT INTO Course VALUES ('Chinese Migration', 'AMES 409');
INSERT INTO Course VALUES ('Queer China', 'AMES 439/WOMENST 439');
INSERT INTO Course VALUES ('Minor Japan', 'AMES 469S');
INSERT INTO Course VALUES ('North Korea', 'AMES 475S');
INSERT INTO Course VALUES ('Language and Migration', 'AMES 489S');
INSERT INTO Course VALUES ('Chinese Media and Pop Culture', 'AMES 535');
INSERT INTO Course VALUES ('Audiovisualities', 'AMES 89S');
INSERT INTO Course VALUES ('Introduction to Film Studies', 'AMI 201/LIT 110');
INSERT INTO Course VALUES ('History of Documentary Films', 'AMI 202');
INSERT INTO Course VALUES ('Animated Film', 'AMI 215/ARTSVIS 328');
INSERT INTO Course VALUES ('Studies in the US Cultural Industries', 'AMI 280AS');
INSERT INTO Course VALUES ('Introduction to Global Los Angeles', 'AMI 283A');
INSERT INTO Course VALUES ('Arts, Film, or Media Practicum', 'AMI 295A');
INSERT INTO Course VALUES ('Moving Image Practice', 'AMI 301S');
INSERT INTO Course VALUES ('Writing about Films', 'AMI 306S');
INSERT INTO Course VALUES ('Hashtags Memes, Digital Tribes', 'AMI 308S');
INSERT INTO Course VALUES ('Editing for Film and Video', 'AMI 357S');
INSERT INTO Course VALUES ('Generative Media Authorship', 'AMI 575S');
INSERT INTO Course VALUES ('Continental Latin American Cinema', 'AMI 89S');
INSERT INTO Course VALUES ('Castles of Europe', 'ARTHIST 190S');
INSERT INTO Course VALUES ('The Aegean Bronze Age', 'ARTHIST 205');
INSERT INTO Course VALUES ('Art of greece and rome', 'ARTHIST 210');
INSERT INTO Course VALUES ('Gothic Cathedrals', 'ARTHIST 225');
INSERT INTO Course VALUES ('Japanese Art, 1600 to the Present', 'ARTHIST 232');
INSERT INTO Course VALUES ('Art in Renaissance Italy', 'ARTHIST 255');
INSERT INTO Course VALUES ('Michelangelo in Context', 'ARTHIST 259');
INSERT INTO Course VALUES ('Art an Architecture in Early Modern France', 'ARTHIST 268');
INSERT INTO Course VALUES ('Russian Art and Politics', 'ARTHIST 287');
INSERT INTO Course VALUES ('The Social History of Impressionism', 'ARTHIST 298');
INSERT INTO Course VALUES ('History of Photography', 'ARTHIST 303');
INSERT INTO Course VALUES ('Architecture and Urbanism in NYC', 'ARTHIST 390A/ENGLISH 390A');
INSERT INTO Course VALUES ('Introduction to the Arts of the Moving Image', 'ARTSVIS 102');
INSERT INTO Course VALUES ('Introduction to Photography', 'ARTSVIS 115S');
INSERT INTO Course VALUES ('Introduction to Digital Photography', 'ARTSVIS 119S');
INSERT INTO Course VALUES ('Compositional Painting', 'ARTSVIS 120');
INSERT INTO Course VALUES ('Experimental Interface Design', 'ARTSVIS 198');
INSERT INTO Course VALUES ('Drawing', 'ARTSVIS 199');
INSERT INTO Course VALUES ('Intermediate Drawing', 'ARTSVIS 205');
INSERT INTO Course VALUES ('Digital Imaging', 'ARTSVIS 206');
INSERT INTO Course VALUES ('Virtual Form and Space', 'ARTSVIS 208LS');
INSERT INTO Course VALUES ('3D Modeling and Animation', 'ARTSVIS 209/VMS 351');
INSERT INTO Course VALUES ('Photography', 'ARTSVIS 219S');
INSERT INTO Course VALUES ('Graphic Design in Multimedia', 'ARTSVIS 223');
INSERT INTO Course VALUES ('Experimental Filmmaking', 'ARTSVIS 229S');
INSERT INTO Course VALUES ('Small Town USA', 'ARTSVIS 232S');
INSERT INTO Course VALUES ('Motion Graphics Film and Video', 'ARTSVIS 236S');
INSERT INTO Course VALUES ('Senior Capstone in Visual Prac', 'ARTSVIS 498S');
INSERT INTO Course VALUES ('Introductory Biochemistry I', 'BIOCHEM 301');
INSERT INTO Course VALUES ('Science Communication', 'BIOETHIC 502');
INSERT INTO Course VALUES ('Genetics, Genomics, & Society', 'BIOLOGY 156');
INSERT INTO Course VALUES ('Molecular Biology', 'BIOLOGY 201');
INSERT INTO Course VALUES ('Genetics and Evolution', 'BIOLOGY 202');
INSERT INTO Course VALUES ('Ecology and Human Health', 'BIOLOGY 209');
INSERT INTO Course VALUES ('Biological Clocks', 'BIOLOGY 218');
INSERT INTO Course VALUES ('Cell and Developmental Biology', 'BIOLOGY 220');
INSERT INTO Course VALUES ('Developmental Neurobiology', 'BIOLOGY 223');
INSERT INTO Course VALUES ('BIOLOGY Independent Study', 'BIOLOGY 293');
INSERT INTO Course VALUES ('Biological Data Analysis', 'BIOLOGY 304');
INSERT INTO Course VALUES ('Developmental and Stem Cell Bio Colloquium', 'BIOLOGY 415S');
INSERT INTO Course VALUES ('Introduction to Biophysics', 'BIOLOGY 418');
INSERT INTO Course VALUES ('Cancer Genetics', 'BIOLOGY 420');
INSERT INTO Course VALUES ('Biology of Nervous System Diseases', 'BIOLOGY 421S');
INSERT INTO Course VALUES ('Sensory Biology', 'BIOLOGY 427');
INSERT INTO Course VALUES ('How Organism Move', 'BIOLOGY 429');
INSERT INTO Course VALUES ('Genes in an Ecological Context', 'BIOLOGY 453');
INSERT INTO Course VALUES ('Principles of Immunology', 'BIOLOGY 515');
INSERT INTO Course VALUES ('Medical Instrumentation in the Developing World', 'BME 195FS');
INSERT INTO Course VALUES ('Quantitative Physiology with Biostatistical Applications', 'BME 244');
INSERT INTO Course VALUES ('Modeling Cellular and Molecular Systems', 'BME 260');
INSERT INTO Course VALUES ('Signal Processing', 'BME 271');
INSERT INTO Course VALUES ('Bioelectricity', 'BME 301');
INSERT INTO Course VALUES ('Biomaterials and biomechanics', 'BME 302');
INSERT INTO Course VALUES ('Instrumentation', 'BME 354');
INSERT INTO Course VALUES ('Neuroengineering', 'BME 503');
INSERT INTO Course VALUES ('Computational Neuroengineering', 'BME 513');
INSERT INTO Course VALUES ('Practical Method in CE', 'CEE 205');
INSERT INTO Course VALUES ('Introduction to Physiology', 'CELLBIO 503');
INSERT INTO Course VALUES ('Core Concepts in Chemistry', 'CHEM 101');
INSERT INTO Course VALUES ('Honors Chemistry', 'CHEM 110');
INSERT INTO Course VALUES ('Organic Chemistry I', 'CHEM 201');
INSERT INTO Course VALUES ('Organic Chemistry II', 'CHEM 202');
INSERT INTO Course VALUES ('Modern Applications of Chemical Principles', 'CHEM 210');
INSERT INTO Course VALUES ('Chemistry, Technology, and Society', 'CHEM 91');
INSERT INTO Course VALUES ('Introduction to Chemistry', 'CHEM 99');
INSERT INTO Course VALUES ('Chinese for Beginners I', 'CHINESE 101');
INSERT INTO Course VALUES ('Literacy in Chinese II', 'CHINESE 232');
INSERT INTO Course VALUES ('Translation and Intepretation', 'CHINESE 332');
INSERT INTO Course VALUES ('Advanced Literacy in Chinese', 'CHINESE 333');
INSERT INTO Course VALUES ('Issues in Modern Chinese', 'CHINESE 334');
INSERT INTO Course VALUES ('Themes in Modern Chinese', 'CHINESE 435S');
INSERT INTO Course VALUES ('Modern Chinese Culture', 'CHINESE 455');
INSERT INTO Course VALUES ('Chinese Culture and Society', 'CHINESE 456');
INSERT INTO Course VALUES ('Introduction to Computer Science', 'COMPSCI 101');
INSERT INTO Course VALUES ('Computing and the Brain', 'COMPSCI 103');
INSERT INTO Course VALUES ('Data Structures and Algorithms', 'COMPSCI 201');
INSERT INTO Course VALUES ('Everything Data', 'COMPSCI 216');
INSERT INTO Course VALUES ('Discrete Math for Computer Science', 'COMPSCI 230');
INSERT INTO Course VALUES ('Computer Architecture', 'COMPSCI 250/ECE 250');
INSERT INTO Course VALUES ('Introduction to Computational Genomics', 'COMPSCI 260');
INSERT INTO Course VALUES ('Introduction to Artificial Intelligence', 'COMPSCI 270');
INSERT INTO Course VALUES ('Algorithmic Foundation of Data Science', 'COMPSCI 290');
INSERT INTO Course VALUES ('Computer Security', 'COMPSCI 290');
INSERT INTO Course VALUES ('Data Engineering', 'COMPSCI 290');
INSERT INTO Course VALUES ('Data Science Competition', 'COMPSCI 290');
INSERT INTO Course VALUES ('Mobile Software Design', 'COMPSCI 290');
INSERT INTO Course VALUES ('Web Application Development', 'COMPSCI 290');
INSERT INTO Course VALUES ('Digital 3D Geometry', 'COMPSCI 290/MATH 290');
INSERT INTO Course VALUES ('Software Design and Implementation', 'COMPSCI 308');
INSERT INTO Course VALUES ('CompSci Problem Solving Seminar', 'COMPSCI 309S');
INSERT INTO Course VALUES ('Introduction to Operating Systems', 'COMPSCI 310');
INSERT INTO Course VALUES ('Introduction to Database Systems', 'COMPSCI 316');
INSERT INTO Course VALUES ('Introduction to the Design and Analysis of Algorithms', 'COMPSCI 330');
INSERT INTO Course VALUES ('Technical and Social Analysis of Information and the Internet', 'COMPSCI 342S');
INSERT INTO Course VALUES ('Computer Network Architecture', 'COMPSCI 356');
INSERT INTO Course VALUES ('Elements of Machine Learning', 'COMPSCI 371D');
INSERT INTO Course VALUES ('COMPSCI Research Independent Study', 'COMPSCI 393');
INSERT INTO Course VALUES ('Delivering Software', 'COMPSCI 408S');
INSERT INTO Course VALUES ('Distributed Information Systems', 'COMPSCI 512');
INSERT INTO Course VALUES ('Data Intensive Comp Systems', 'COMPSCI 516');
INSERT INTO Course VALUES ('Computer Vision', 'COMPSCI 527');
INSERT INTO Course VALUES ('Design and Analysis of Algorithms', 'COMPSCI 532');
INSERT INTO Course VALUES ('Compiler Construction', 'COMPSCI 553');
INSERT INTO Course VALUES ('Artificial Intelligence', 'COMPSCI 570');
INSERT INTO Course VALUES ('Machine Learning', 'COMPSCI 571');
INSERT INTO Course VALUES ('Advanced Computer Security', 'COMPSCI 590');
INSERT INTO Course VALUES ('Graph Algorithm', 'COMPSCI 590');
INSERT INTO Course VALUES ('Algorithms in the Real Life', 'COMPSCI 590');
INSERT INTO Course VALUES ('Randomized Algorithm', 'COMPSCI 630');
INSERT INTO Course VALUES ('Approximation Algorithm', 'COMPSCI 632');
INSERT INTO Course VALUES ('Intro Creating Mobile Apps', 'COMPSCI 89S');
INSERT INTO Course VALUES ('Course Name', 'Course Number');
INSERT INTO Course VALUES ('Medical Anthropology', 'CULANT 424');
INSERT INTO Course VALUES ('Introduction to Cultural Anthropology', 'CULANTH 101');
INSERT INTO Course VALUES ('Music, Social Life, and Scenes', 'CULANTH 137/MUSIC 137');
INSERT INTO Course VALUES ('Advertising and Society: Global Perspective', 'CULANTH 170D');
INSERT INTO Course VALUES ('Advocacy for Change', 'CULANTH 190FS');
INSERT INTO Course VALUES ('Making Your Case', 'CULANTH 190FS');
INSERT INTO Course VALUES ('Technology and Social Change', 'CULANTH 190FS');
INSERT INTO Course VALUES ('Self and society', 'CULANTH 204');
INSERT INTO Course VALUES ('Anthropology of Law', 'CULANTH 206');
INSERT INTO Course VALUES ('Politics of Food', 'CULANTH 238S');
INSERT INTO Course VALUES ('Migrant China', 'CULANTH 241');
INSERT INTO Course VALUES ('Critical Food Studies', 'CULANTH 290');
INSERT INTO Course VALUES ('Urban Violence', 'CULANTH 290S');
INSERT INTO Course VALUES ('Theoretical Foundations', 'CULANTH 301');
INSERT INTO Course VALUES ('Fieldwork Methods', 'CULANTH 302');
INSERT INTO Course VALUES ('Global Cities', 'CULANTH 465S');
INSERT INTO Course VALUES ('Music as Mirror, Mediator', 'CULANTH 89S');
INSERT INTO Course VALUES ('Introduction to Dance', 'DANCE 101');
INSERT INTO Course VALUES ('Beginning Ballet', 'DANCE 120');
INSERT INTO Course VALUES ('Advanced Beginning Ballet', 'DANCE 121');
INSERT INTO Course VALUES ('African Dance Tech I', 'DANCE 130');
INSERT INTO Course VALUES ('Capoeira', 'DANCE 131');
INSERT INTO Course VALUES ('Jazz Dance I', 'DANCE 140');
INSERT INTO Course VALUES ('Hip Hop II', 'DANCE 143');
INSERT INTO Course VALUES ('Modern Dance III', 'DANCE 210');
INSERT INTO Course VALUES ('Jazz Dance II', 'DANCE 240');
INSERT INTO Course VALUES ('Contemporary Documentary Film', 'DOCST 270/PUBPOL 374');
INSERT INTO Course VALUES ('Photographic Essay', 'DOCST 89S');
INSERT INTO Course VALUES ('Fundamentals of ECE', 'ECE 110');
INSERT INTO Course VALUES ('Introduction to Microelectronic Devices and Circuits', 'ECE 230');
INSERT INTO Course VALUES ('Electromagnetic Fields', 'ECE 270');
INSERT INTO Course VALUES ('Introduction to Signals and Systems', 'ECE 280');
INSERT INTO Course VALUES ('Fundamental of Microelectronic Circuit', 'ECE 331');
INSERT INTO Course VALUES ('Digital Systems', 'ECE 350/COMPSCI 350');
INSERT INTO Course VALUES ('Introduction to Random Signals and Noise', 'ECE 380');
INSERT INTO Course VALUES ('Linear Control Systems', 'ECE 382');
INSERT INTO Course VALUES ('Engineering Software for Maintainability', 'ECE 458');
INSERT INTO Course VALUES ('Advanced Computer Architecture', 'ECE 552/CS 550');
INSERT INTO Course VALUES ('Cloud Computing', 'ECE 563');
INSERT INTO Course VALUES ('Random Signals and Noise', 'ECE 581');
INSERT INTO Course VALUES ('Engineering Robust Server Software', 'ECE 590');
INSERT INTO Course VALUES ('Economic Principles', 'ECON 101');
INSERT INTO Course VALUES ('Focus game theory', 'ECON 138');
INSERT INTO Course VALUES ('Financial Accounting', 'ECON 174');
INSERT INTO Course VALUES ('Introduction to Game Theory', 'ECON 190FS');
INSERT INTO Course VALUES ('Intermediate Microeconomics I', 'ECON 201');
INSERT INTO Course VALUES ('Intermediate Microeconomics II', 'ECON 205');
INSERT INTO Course VALUES ('Introduction to Econometrics', 'ECON 208');
INSERT INTO Course VALUES ('Intermediate Macroeconomics', 'ECON 210');
INSERT INTO Course VALUES ('Practical Financial Markets', 'ECON 256');
INSERT INTO Course VALUES ('Advanced Financial and Managerial Accounting', 'ECON 274');
INSERT INTO Course VALUES ('Shakespeare and Fin Markets', 'ECON 290S');
INSERT INTO Course VALUES ('History of International Financial and Monetary Crises', 'ECON 305');
INSERT INTO Course VALUES ('Understanding Financial Bubbles and Crises', 'ECON 307A');
INSERT INTO Course VALUES ('Anthropology of Money', 'ECON 309/CULANTH 350');
INSERT INTO Course VALUES ('History of Econocmics Thought', 'ECON 311');
INSERT INTO Course VALUES ('The Uses of Economics', 'ECON 313');
INSERT INTO Course VALUES ('The History of Modern Macroeconomics', 'ECON 314S');
INSERT INTO Course VALUES ('The Philosophy and Methodology of Economics', 'ECON 319');
INSERT INTO Course VALUES ('Energy economics', 'ECON 325');
INSERT INTO Course VALUES ('The Contemporary Art Market', 'ECON 343');
INSERT INTO Course VALUES ('History of Art Markets', 'ECON 344');
INSERT INTO Course VALUES ('Urban Economics', 'ECON 345');
INSERT INTO Course VALUES ('Philosophy of Entreprenuership', 'ECON 346/PHIL 447');
INSERT INTO Course VALUES ('Women in the Economy', 'ECON 348');
INSERT INTO Course VALUES ('Financial Institutions', 'ECON 353');
INSERT INTO Course VALUES ('Money, Banking and Financial Markets', 'ECON 353');
INSERT INTO Course VALUES ('International Trade', 'ECON 355A');
INSERT INTO Course VALUES ('People and Poverty', 'ECON 369');
INSERT INTO Course VALUES ('Global Capital Markets', 'ECON 370/ECON 470');
INSERT INTO Course VALUES ('Intermediate Finance', 'ECON 372');
INSERT INTO Course VALUES ('Corporate Finance', 'ECON 373');
INSERT INTO Course VALUES ('The Economics of Entrepreneurship', 'ECON 375');
INSERT INTO Course VALUES ('The Economics of Financial Derivatives & Financial Engineering', 'ECON 377A');
INSERT INTO Course VALUES ('Asset Management', 'ECON 390');
INSERT INTO Course VALUES ('Race and Higher Education in the South', 'ECON 390');
INSERT INTO Course VALUES ('Race and Labor Markets', 'ECON 390');
INSERT INTO Course VALUES ('Financial Crises/Globalization', 'ECON 390A');
INSERT INTO Course VALUES ('ECON Independent Study on LBO Modeling', 'ECON 391');
INSERT INTO Course VALUES ('Forecasting financial market', 'ECON 413');
INSERT INTO Course VALUES ('International Finance', 'ECON 455');
INSERT INTO Course VALUES ('Law and Economics', 'ECON 463');
INSERT INTO Course VALUES ('Industrial Organization and Competitive Strategy', 'ECON 464');
INSERT INTO Course VALUES ('Financial Markets and Investment', 'ECON 471');
INSERT INTO Course VALUES ('ECON Honors Seminar I', 'ECON 495S');
INSERT INTO Course VALUES ('ECON Honors Seminar II', 'ECON 496S');
INSERT INTO Course VALUES ('Global Responses to the Rise of China', 'ECON 550S');
INSERT INTO Course VALUES ('Mathematical Finance', 'ECON 673/MATH 581');
INSERT INTO Course VALUES ('Foundations of Education', 'EDUC 101');
INSERT INTO Course VALUES ('Philosophy of Education', 'EDUC 101S');
INSERT INTO Course VALUES ('Rethinking education', 'EDUC 111FS');
INSERT INTO Course VALUES ('Digitial Documentary Photography', 'EDUC 209');
INSERT INTO Course VALUES ('Literacy Through Photography', 'EDUC 244');
INSERT INTO Course VALUES ('Asian Americans in Higher Education', 'EDUC 345S');
INSERT INTO Course VALUES ('Computational Methods in Engineering', 'EGR 103');
INSERT INTO Course VALUES ('Engineering Innovation', 'EGR 121');
INSERT INTO Course VALUES ('Mechanics of Solids', 'EGR 201');
INSERT INTO Course VALUES ('Electrical fund of mechanics', 'EGR 224');
INSERT INTO Course VALUES ('Dynamics', 'EGR 244');
INSERT INTO Course VALUES ('Energy and Environment', 'ENERGY 231/ENVIRON 231/EOS 330/ENERGY 330');
INSERT INTO Course VALUES ('Green Germany', 'ENERGY 364');
INSERT INTO Course VALUES ('Renewable Energy Development', 'ENERGY 590');
INSERT INTO Course VALUES ('Energy Technology', 'ENERGY 610');
INSERT INTO Course VALUES ('Introduction to Creative Writing', 'ENGLISH 110S');
INSERT INTO Course VALUES ('Language and Identity', 'ENGLISH 195FS');
INSERT INTO Course VALUES ('Introduction to the Writing of Poetry', 'ENGLISH 220S');
INSERT INTO Course VALUES ('Transforming fiction to stage/screen', 'ENGLISH 227');
INSERT INTO Course VALUES ('American Crime, 1800-1914', 'ENGLISH 290S');
INSERT INTO Course VALUES ('James Joyce', 'ENGLISH 309');
INSERT INTO Course VALUES ('Screenwriting', 'THEATRST 273/ENGLISH 317S');
INSERT INTO Course VALUES ('Shakespeare After 1600', 'ENGLISH 337');
INSERT INTO Course VALUES ('19th Century British Novel', 'ENGLISH 345');
INSERT INTO Course VALUES ('Shakespeare: Now and Then', 'ENGLISH 390');
INSERT INTO Course VALUES ('Space after Space Travel', 'ENGLISH 90');
INSERT INTO Course VALUES ('Spy Novels', 'ENGLISH 90S');
INSERT INTO Course VALUES ('Introduction to Environmental Sciences and Policy', 'ENVIRON 102');
INSERT INTO Course VALUES ('Integrating Environmental Science and Policy', 'ENVIRON 201');
INSERT INTO Course VALUES ('Conserving Variety of Life', 'ENVIRON 210D');
INSERT INTO Course VALUES ('Field Methods in Earth and Environmental Sciences', 'ENVIRON 226S/EOS 226S');
INSERT INTO Course VALUES ('Biodiversity and Field Methods', 'ENVIRON 240');
INSERT INTO Course VALUES ('Sustainability Theory/practice', 'ENVIRON 245');
INSERT INTO Course VALUES ('Urban Environmental Design', 'ENVIRON 253S');
INSERT INTO Course VALUES ('People, Plants, and Pollution', 'ENVIRON 274');
INSERT INTO Course VALUES ('Water in the changing world', 'ENVIRON 390');
INSERT INTO Course VALUES ('Environmental Science', 'ENVIRON 581');
INSERT INTO Course VALUES ('After the Spill', 'ENVIRON 89S');
INSERT INTO Course VALUES ('The Dynamic Earth', 'EOS 101');
INSERT INTO Course VALUES ('The Dynamic Oceans', 'EOS 102/BIOLOGY 157');
INSERT INTO Course VALUES ('Atmosphere and Ocean Dynamics', 'EOS 202');
INSERT INTO Course VALUES ('The Surface of the Earth', 'EOS 203S');
INSERT INTO Course VALUES ('Evolution of Earth', 'EOS 204');
INSERT INTO Course VALUES ('Meteorites & Solar System History', 'EOS 230');
INSERT INTO Course VALUES ('Global Warming', 'EOS 355');
INSERT INTO Course VALUES ('Geology of Yellowstone', 'EOS 403');
INSERT INTO Course VALUES ('Introduction to Evolutionary Anthropology', 'EVANTH 101');
INSERT INTO Course VALUES ('Evolutionary Anthropology', 'EVANTH 221FS');
INSERT INTO Course VALUES ('Bodies of Evidence: Introduction to Forensic Anthropology', 'EVANTH 230');
INSERT INTO Course VALUES ('Primate Behavioral Ecology', 'EVANTH 253');
INSERT INTO Course VALUES ('Primate Conservation', 'EVANTH 359S');
INSERT INTO Course VALUES ('Cognitive Neuroscience and Law', 'FOCUS 195FS');
INSERT INTO Course VALUES ('Game Theory Focus', 'FOCUS 195FS');
INSERT INTO Course VALUES ('Special Topics in Focus (What If)', 'FOCUS 195FS');
INSERT INTO Course VALUES ('Elementary French I', 'FRENCH 101');
INSERT INTO Course VALUES ('Elementary French II', 'FRENCH 102');
INSERT INTO Course VALUES ('Intensive Elementary French', 'FRENCH 111');
INSERT INTO Course VALUES ('Intermediate French', 'FRENCH 203');
INSERT INTO Course VALUES ('Intensive Intermediate French', 'FRENCH 212');
INSERT INTO Course VALUES ('Advanced French Language/Writing Workshop', 'FRENCH 301');
INSERT INTO Course VALUES ('Cultural and Literary Perspectives', 'FRENCH 302S');
INSERT INTO Course VALUES ('French Current affairs', 'FRENCH 303');
INSERT INTO Course VALUES ('Reading Literature in French', 'FRENCH 306');
INSERT INTO Course VALUES ('Free Speech France - USA', 'FRENCH 335');
INSERT INTO Course VALUES ('Pleasure of Reading', 'FRENCH 339S');
INSERT INTO Course VALUES ('French Culture (Duke in Paris)', 'FRENCH 345A');
INSERT INTO Course VALUES ('French Literature (Duke in Paris)', 'FRENCH 346A');
INSERT INTO Course VALUES ('Yesterday''s Classics/Today''s Movies', 'FRENCH 415');
INSERT INTO Course VALUES ('The Danger of Reading', 'FRENCH 420');
INSERT INTO Course VALUES ('First-Year German I', 'GERMAN 101');
INSERT INTO Course VALUES ('First-Year German II', 'GERMAN 102');
INSERT INTO Course VALUES ('Intermediate German I', 'GERMAN 203');
INSERT INTO Course VALUES ('Fairy tales: Grimms to Disney', 'GERMAN 262');
INSERT INTO Course VALUES ('Advanced German', 'GERMAN 305S');
INSERT INTO Course VALUES ('German Literature and Culture', 'GERMAN 430S');
INSERT INTO Course VALUES ('Fundamentals of Global Health', 'GLHLTH 101');
INSERT INTO Course VALUES ('History of Chinese Medicine', 'GLHLTH 142/HISTORY 239');
INSERT INTO Course VALUES ('Food, Farming, and Feminism', 'GLHLTH 225/WST 275');
INSERT INTO Course VALUES ('Ethics of Infectious Disease Control', 'GLHLTH 341');
INSERT INTO Course VALUES ('Fundamentals of Global Mental Health', 'GLHLTH 363/PSY 323');
INSERT INTO Course VALUES ('Research Methods in Global Health', 'GLHLTH 371');
INSERT INTO Course VALUES ('Supply, Financing, and Organization in Health', 'GLHLTH 690');
INSERT INTO Course VALUES ('Thinking Gender (Sem)', 'GSF 199S');
INSERT INTO Course VALUES ('Nature, Gender, and Culture', 'GSF 366');
INSERT INTO Course VALUES ('Intermediate Hindi', 'HINDI 203');
INSERT INTO Course VALUES ('Old Worlds New Histories', 'HISTORY 105');
INSERT INTO Course VALUES ('Anarchism and Its Discontent', 'HISTORY 116');
INSERT INTO Course VALUES ('Early Modern Europe', 'HISTORY 117');
INSERT INTO Course VALUES ('American Dreams and American Realities', 'HISTORY 130D');
INSERT INTO Course VALUES ('Cold War America', 'HISTORY 156');
INSERT INTO Course VALUES ('Asia in Global History', 'HISTORY 162S');
INSERT INTO Course VALUES ('Gandhi, King, Mandela', 'HISTORY 190FS');
INSERT INTO Course VALUES ('Survey of Modern China 1800-Present', 'HISTORY 223');
INSERT INTO Course VALUES ('Greek History', 'HISTORY 230');
INSERT INTO Course VALUES ('Political Nonviolence', 'HISTORY 238');
INSERT INTO Course VALUES ('Greek and Roman Law', 'HISTORY 240');
INSERT INTO Course VALUES ('Medieval European History', 'HISTORY 254');
INSERT INTO Course VALUES ('Germany Confronts Holocaust', 'HISTORY 261/GERMAN 387');
INSERT INTO Course VALUES ('History of Modern Terrorism', 'HISTORY 279');
INSERT INTO Course VALUES ('Europe in the 20th Century', 'HISTORY 286');
INSERT INTO Course VALUES ('Hamilton and his world', 'HISTORY 309');
INSERT INTO Course VALUES ('US Social Movements', 'HISTORY 344');
INSERT INTO Course VALUES ('Violent Jihad in the 20th century', 'HISTORY 359');
INSERT INTO Course VALUES ('American Business History', 'HISTORY 364');
INSERT INTO Course VALUES ('Apartheid/Democracy', 'HISTORY 386');
INSERT INTO Course VALUES ('Urbanization in China', 'HOUSECS 59');
INSERT INTO Course VALUES ('House Course: Social Inequality in China', 'HOUSECS 59');
INSERT INTO Course VALUES ('Exploring Religion', 'HOUSECS 59');
INSERT INTO Course VALUES ('Condoms and Counseling', 'HOUSECS 59');
INSERT INTO Course VALUES ('Paradoxes', 'HOUSECS 59');
INSERT INTO Course VALUES ('Learning to Fail', 'I&E 256');
INSERT INTO Course VALUES ('Technology Commercialization', 'I&E 281');
INSERT INTO Course VALUES ('Entrepreneurship Keystone', 'I&E 352');
INSERT INTO Course VALUES ('Innovation & Entrepreneurship', 'I&E 352');
INSERT INTO Course VALUES ('Anarchism', 'ICS 166S');
INSERT INTO Course VALUES ('Comparative Approaches to Global Issues', 'ICS 195');
INSERT INTO Course VALUES ('Understanding Middle East', 'ICS 205');
INSERT INTO Course VALUES ('ICS Capstone', 'ICS 495');
INSERT INTO Course VALUES ('Digital Cities', 'ISIS 380S');
INSERT INTO Course VALUES ('Introduction to Programming and User Interface Design', 'ISS 320S');
INSERT INTO Course VALUES ('Elementary Italian II', 'ITALIAN 102');
INSERT INTO Course VALUES ('Elementary Japanese I', 'JPN 101');
INSERT INTO Course VALUES ('Elementary Japanese II', 'JPN 102');
INSERT INTO Course VALUES ('Intermediate Japanese I', 'JPN 203');
INSERT INTO Course VALUES ('Intermediate Japanese II', 'JPN 204');
INSERT INTO Course VALUES ('Advanced Japanese I', 'JPN 305');
INSERT INTO Course VALUES ('Advanced Japanese II', 'JPN 306');
INSERT INTO Course VALUES ('Elementary Korean I', 'KOREAN 101');
INSERT INTO Course VALUES ('Elementary Korean II', 'KOREAN 102');
INSERT INTO Course VALUES ('Intermediate Korean I', 'KOREAN 203');
INSERT INTO Course VALUES ('Intermediate Korean II', 'KOREAN 204');
INSERT INTO Course VALUES ('Advanced Korean II', 'KOREAN 306S');
INSERT INTO Course VALUES ('Issues in Korean Language/Society', 'KOREAN 407S');
INSERT INTO Course VALUES ('Latin Epic', 'LATIN 324S');
INSERT INTO Course VALUES ('Language, Lession, and Loss', 'LINGUIST 123FS');
INSERT INTO Course VALUES ('Special Topics in Linguistics', 'LINGUIST 190FS');
INSERT INTO Course VALUES ('Introduction to Linguistics', 'LINGUIST 201/CULANTH 201');
INSERT INTO Course VALUES ('Languages of the world', 'LINGUIST 202');
INSERT INTO Course VALUES ('Neuroscience and Reading', 'LINGUIST 211FS');
INSERT INTO Course VALUES ('The Politics of Language', 'LINGUIST 213FS');
INSERT INTO Course VALUES ('Neuroscience/Human Language', 'LINGUIST 216FS');
INSERT INTO Course VALUES ('Gender and Lanuage', 'LINGUIST 364');
INSERT INTO Course VALUES ('Aliens and other planets', 'LIT 190S');
INSERT INTO Course VALUES ('Introduction to Transgender', 'LIT 190S');
INSERT INTO Course VALUES ('Media Bodies: Clouds/Porn/Anime', 'LIT 190S');
INSERT INTO Course VALUES ('Introduction to Global Cultural Studies', 'LIT 201');
INSERT INTO Course VALUES ('Modern European Short Fiction', 'LIT 244');
INSERT INTO Course VALUES ('Theory Today', 'LIT 301S');
INSERT INTO Course VALUES ('Special Topics In Literature', 'LIT 390S');
INSERT INTO Course VALUES ('Gender and Law', 'LIT 430');
INSERT INTO Course VALUES ('Post WWII World Literature', 'LIT 690');
INSERT INTO Course VALUES ('Capitalism, Crisis, Communism', 'LIT 89S');
INSERT INTO Course VALUES ('Laboratory Calculus I', 'MATH 111');
INSERT INTO Course VALUES ('Laboratory Calculus II', 'MATH 112L');
INSERT INTO Course VALUES ('Introductory Calculus II with Applications', 'MATH 122L');
INSERT INTO Course VALUES ('Math In Genetics And Genomics', 'MATH 168S');
INSERT INTO Course VALUES ('Math Everywhere', 'MATH 181');
INSERT INTO Course VALUES ('Multivariable Calculus for Economics', 'MATH 202');
INSERT INTO Course VALUES ('Multivariable Calculus', 'MATH 212');
INSERT INTO Course VALUES ('Linear Algebra and Differential Equations', 'MATH 216');
INSERT INTO Course VALUES ('Linear Algebra and Matrices', 'MATH 218');
INSERT INTO Course VALUES ('Linear Algebra and Applications', 'MATH 221');
INSERT INTO Course VALUES ('Advanced Multivariable Calculus', 'MATH 222');
INSERT INTO Course VALUES ('Introduction to Applied Math', 'MATH 240');
INSERT INTO Course VALUES ('Math Problem Solving Seminar', 'MATH 281S');
INSERT INTO Course VALUES ('Introduction to Cryptography', 'MATH 304');
INSERT INTO Course VALUES ('Number Theory', 'MATH 305S');
INSERT INTO Course VALUES ('Gerrymandering', 'MATH 309');
INSERT INTO Course VALUES ('Complex Analysis', 'MATH 333');
INSERT INTO Course VALUES ('Advanced Introduction to Probability', 'MATH 340');
INSERT INTO Course VALUES ('Geometry', 'MATH 342S');
INSERT INTO Course VALUES ('Ordinary and Partial Differential Equations', 'MATH 353');
INSERT INTO Course VALUES ('Elementary Differential Equations', 'MATH 356');
INSERT INTO Course VALUES ('Mathematical Numerical Analysis', 'MATH 361S');
INSERT INTO Course VALUES ('Applied Combinatorics', 'MATH 371');
INSERT INTO Course VALUES ('Introduction to Abstract Algebra', 'MATH 401');
INSERT INTO Course VALUES ('Advanced Linear Algebra', 'MATH 403');
INSERT INTO Course VALUES ('Topology with Applications', 'MATH 412');
INSERT INTO Course VALUES ('Differential Geometry', 'MATH 421');
INSERT INTO Course VALUES ('Advanced Calculus', 'MATH 431');
INSERT INTO Course VALUES ('Fundamental Analysis', 'MATH 431');
INSERT INTO Course VALUES ('Nonlinear Ordinary Differential Equations', 'MATH 451S');
INSERT INTO Course VALUES ('Introduction to Partial Differential Equations', 'MATH 453');
INSERT INTO Course VALUES ('Introduction to High Dimensional Data Analysis', 'MATH 465');
INSERT INTO Course VALUES ('Category Theory', 'MATH 490');
INSERT INTO Course VALUES ('Introduction to Algebraic Structures I', 'MATH 501');
INSERT INTO Course VALUES ('Basic Analysis I', 'MATH 531');
INSERT INTO Course VALUES ('Ordinary Differential Equation', 'MATH 555');
INSERT INTO Course VALUES ('Math Modeling', 'MATH 577');
INSERT INTO Course VALUES ('Commutative Algebra', 'MATH 602');
INSERT INTO Course VALUES ('Advanced Differential Geometry', 'MATH 621');
INSERT INTO Course VALUES ('Real Analysis', 'MATH 631');
INSERT INTO Course VALUES ('Advanced Complex Analysis', 'MATH 633');
INSERT INTO Course VALUES ('Relativity of the universe', 'MATH 89S');
INSERT INTO Course VALUES ('Structure and Properties of Solids', 'ME 221');
INSERT INTO Course VALUES ('Fluid Mechanics', 'ME 336');
INSERT INTO Course VALUES ('Control Systems', 'ME 344');
INSERT INTO Course VALUES ('ME Independent Study', 'ME 392');
INSERT INTO Course VALUES ('Special Topics in Markets and Managements', 'MMS 190FS');
INSERT INTO Course VALUES ('Managerial Effectiveness', 'MMS 210');
INSERT INTO Course VALUES ('Marketing Management', 'MMS 220');
INSERT INTO Course VALUES ('Game Changers', 'MMS 230');
INSERT INTO Course VALUES ('Marketing without Borders', 'MMS 272');
INSERT INTO Course VALUES ('Business of Sports', 'MMS 275');
INSERT INTO Course VALUES ('Entrepreneurial Finance and Opportunity', 'MMS 360');
INSERT INTO Course VALUES ('Managerial Finance', 'MMS 370');
INSERT INTO Course VALUES ('International Business', 'MMS 390A');
INSERT INTO Course VALUES ('Markets and Management Capstone', 'MMS 450');
INSERT INTO Course VALUES ('Creative entrepenurship', 'MMS 490');
INSERT INTO Course VALUES ('Sports marketing', 'MMS 490');
INSERT INTO Course VALUES ('Class Voice', 'MUSIC 101');
INSERT INTO Course VALUES ('Class Guitar', 'MUSIC 101');
INSERT INTO Course VALUES ('Djembe Class', 'MUSIC 101');
INSERT INTO Course VALUES ('Classical Piano I', 'MUSIC 103');
INSERT INTO Course VALUES ('Jazz Guitar', 'MUSIC 104-6');
INSERT INTO Course VALUES ('Acoustics and Music', 'MUSIC 126/PHYSICS 136');
INSERT INTO Course VALUES ('World Music', 'MUSIC 130');
INSERT INTO Course VALUES ('Hip-Hop/Rap Music Appreciation', 'MUSIC 145');
INSERT INTO Course VALUES ('The Beatles and the 1960s', 'MUSIC 157');
INSERT INTO Course VALUES ('Introduction to Music Theory (Advanced)', 'MUSIC 161');
INSERT INTO Course VALUES ('Jazz Combo/Improvisation', 'MUSIC 171');
INSERT INTO Course VALUES ('Classical Piano II', 'MUSIC 203');
INSERT INTO Course VALUES ('Voice (Individual)', 'MUSIC 208');
INSERT INTO Course VALUES ('Accompaniment', 'MUSIC 211');
INSERT INTO Course VALUES ('Hollywood Film Music', 'MUSIC 249');
INSERT INTO Course VALUES ('Music History I', 'MUSIC 255S');
INSERT INTO Course VALUES ('Music History II', 'MUSIC 256S');
INSERT INTO Course VALUES ('Music History III', 'MUSIC 257');
INSERT INTO Course VALUES ('Music History IV', 'MUSIC 258');
INSERT INTO Course VALUES ('Music Theory I', 'MUSIC 261');
INSERT INTO Course VALUES ('Theory of tonal music I', 'MUSIC 261');
INSERT INTO Course VALUES ('Arts Entrepreneurship', 'MUSIC 295');
INSERT INTO Course VALUES ('Instrumental Conducting', 'MUSIC 318');
INSERT INTO Course VALUES ('Music Theory II', 'MUSIC 361');
INSERT INTO Course VALUES ('Music Theory IV', 'MUSIC 461');
INSERT INTO Course VALUES ('Special Topics in Analysis and Culture', 'MUSIC 590');
INSERT INTO Course VALUES ('Composers of Influence', 'MUSIC 89S');
INSERT INTO Course VALUES ('Drama Through Music', 'MUSIC 89S');
INSERT INTO Course VALUES ('Biological Bases of Behavior', 'NEUROSCI 101');
INSERT INTO Course VALUES ('Biological Bases of Behavior (Team)', 'NEUROSCI 102');
INSERT INTO Course VALUES ('Neuroscience and Human Language', 'NEUROSCI 116FS');
INSERT INTO Course VALUES ('Fundamentals of Neuroscience', 'NEUROSCI 201');
INSERT INTO Course VALUES ('Medical Neuroscience', 'NEUROSCI 202');
INSERT INTO Course VALUES ('Neuroscience and Religion', 'NEUROSCI 237');
INSERT INTO Course VALUES ('The Mimetic Brain', 'NEUROSCI 242A');
INSERT INTO Course VALUES ('Philosophy and Neuroscience', 'NEUROSCI 252/PHIL 252');
INSERT INTO Course VALUES ('Decision Neuroscience', 'NEUROSCI 258/PSY 258');
INSERT INTO Course VALUES ('Cultured Brain', 'NEUROSCI 290A');
INSERT INTO Course VALUES ('From Neurons to Brain', 'NEUROSCI 322');
INSERT INTO Course VALUES ('Behavioral Neuroimmunology', 'NEUROSCI 373');
INSERT INTO Course VALUES ('Contemporary Neuroscience Methods', 'NEUROSCI 376');
INSERT INTO Course VALUES ('Integrative Neuroscience Lab', 'NEUROSCI 385L');
INSERT INTO Course VALUES ('NEUROSCI Research Independent Study II', 'NEUROSCI 494');
INSERT INTO Course VALUES ('Introduction to Philosophy', 'PHIL 101');
INSERT INTO Course VALUES ('Introduction to Philosophy (Seminar)', 'PHIL 103S');
INSERT INTO Course VALUES ('Logic', 'PHIL 150');
INSERT INTO Course VALUES ('History of Modern Philosophy', 'PHIL 201');
INSERT INTO Course VALUES ('History of Ancient Philosophy', 'PHIL 203');
INSERT INTO Course VALUES ('Metaphysics/Appearence and Thereality', 'PHIL 211');
INSERT INTO Course VALUES ('Philosophy of Mind', 'PHIL 212');
INSERT INTO Course VALUES ('Problems in Ethical Theory', 'PHIL 216');
INSERT INTO Course VALUES ('Philosophy of Sciences', 'PHIL 242');
INSERT INTO Course VALUES ('Symbolic Logic', 'PHIL 250');
INSERT INTO Course VALUES ('Human Rights Practice and Theory', 'PHIL 262');
INSERT INTO Course VALUES ('Chinese Philosophy', 'PHIL 263');
INSERT INTO Course VALUES ('Business Ethics', 'PHIL 270/ETHICS 270');
INSERT INTO Course VALUES ('Existentialism', 'PHIL 285/LIT 285/PHIL 485/LIT 485');
INSERT INTO Course VALUES ('PHILOSOPHY Independent research', 'PHIL 293');
INSERT INTO Course VALUES ('Philosophy of Biology', 'PHIL 314/BIOLOGY 255');
INSERT INTO Course VALUES ('Aristotle', 'PHIL 317/CLST 371');
INSERT INTO Course VALUES ('Philosophy of Economics', 'PHIL 345');
INSERT INTO Course VALUES ('East/West ethics&politics', 'PHIL 463S');
INSERT INTO Course VALUES ('Comparative Ethics', 'PHIL 502S');
INSERT INTO Course VALUES ('Hist/Phil Perspective on Science', 'PHIL 541S');
INSERT INTO Course VALUES ('Metaphysics', 'PHIL 552');
INSERT INTO Course VALUES ('Topics in Philosophy of Mind', 'PHIL 555S');
INSERT INTO Course VALUES ('Early modern philosophy', 'PHIL 629');
INSERT INTO Course VALUES ('Cardio Conditioning', 'PHYSEDU 101');
INSERT INTO Course VALUES ('Circuit Training', 'PHYSEDU 104');
INSERT INTO Course VALUES ('Pilates Mat and Ball', 'PHYSEDU 105');
INSERT INTO Course VALUES ('Fitness for Women', 'PHYSEDU 117');
INSERT INTO Course VALUES ('Basketball', 'PHYSEDU 122');
INSERT INTO Course VALUES ('Advanced Golf', 'PHYSEDU 133');
INSERT INTO Course VALUES ('Endurance Swimming', 'PHYSEDU 137');
INSERT INTO Course VALUES ('Beginning Tennis', 'PHYSEDU 143');
INSERT INTO Course VALUES ('Self Defense for Women', 'PHYSEDU 159');
INSERT INTO Course VALUES ('Mixed Martial Arts Training', 'PHYSEDU 160');
INSERT INTO Course VALUES ('Aikido', 'PHYSEDU 161');
INSERT INTO Course VALUES ('Beginner Tae Kwon Do', 'PHYSEDU 163');
INSERT INTO Course VALUES ('Intermediate/Advanced Tae Kwon Do', 'PHYSEDU 164');
INSERT INTO Course VALUES ('Tai Chi', 'PHYSEDU 166');
INSERT INTO Course VALUES ('Massage Therapy', 'PHYSEDU 172');
INSERT INTO Course VALUES ('YOGA', 'PHYSEDU 174');
INSERT INTO Course VALUES ('Diet and Nutrition', 'PHYSEDU 203');
INSERT INTO Course VALUES ('Women''s Health Issues', 'PHYSEDU 204');
INSERT INTO Course VALUES ('Exercise Physiology', 'PHYSEDU 206');
INSERT INTO Course VALUES ('Theory and Practice of Coaching', 'PHYSEDU 240');
INSERT INTO Course VALUES ('Hot Topics in Health', 'PHYSEDU 89S');
INSERT INTO Course VALUES ('Introduction to Astronomy', 'PHYSICS 134');
INSERT INTO Course VALUES ('Energy in the 21st Century', 'PHYSICS 137S');
INSERT INTO Course VALUES ('General Physics I', 'PHYSICS 141');
INSERT INTO Course VALUES ('General Physics II', 'PHYSICS 142');
INSERT INTO Course VALUES ('Introductory Mechanics', 'PHYSICS 151');
INSERT INTO Course VALUES ('Introductory Electricity, Magnetism, and Optics', 'PHYSICS 152');
INSERT INTO Course VALUES ('Frontiers of 21st Century Physics', 'PHYSICS 160');
INSERT INTO Course VALUES ('Optics and Modern Physics', 'PHYSICS 264');
INSERT INTO Course VALUES ('Introduction to Astrophysics', 'PHYSICS 305');
INSERT INTO Course VALUES ('Intermediate Mechanics', 'PHYSICS 361');
INSERT INTO Course VALUES ('Electricity and Magnetism', 'PHYSICS 362');
INSERT INTO Course VALUES ('Intermediate Electrodynamics', 'PHYSICS 362');
INSERT INTO Course VALUES ('Thermal Physics', 'PHYSICS 363');
INSERT INTO Course VALUES ('Advanced Physics Laboratory & Seminar', 'PHYSICS 417');
INSERT INTO Course VALUES ('Quantum Mechanics I', 'PHYSICS 464');
INSERT INTO Course VALUES ('PHYSICS Independent Study', 'PHYSICS 491');
INSERT INTO Course VALUES ('PHYSICS Research Independent Study', 'PHYSICS 493');
INSERT INTO Course VALUES ('Introduction Nuclear/Particle Physics', 'PHYSICS 505');
INSERT INTO Course VALUES ('Nonlinear Dynamics', 'PHYSICS 513/CS 524');
INSERT INTO Course VALUES ('Computational Physics', 'PHYSICS 566');
INSERT INTO Course VALUES ('Connected by Sound', 'PHYSICS 89S');
INSERT INTO Course VALUES ('Algorithmic Journalism', 'PJMS 361');
INSERT INTO Course VALUES ('Rules of Power', 'POLSCI 115');
INSERT INTO Course VALUES ('Introduction to Political Economy', 'POLSCI 145/ECON 119');
INSERT INTO Course VALUES ('Introduction to Security, Peace and Conflict', 'POLSCI 160D');
INSERT INTO Course VALUES ('Ancient and Modern', 'POLSCI 170FS');
INSERT INTO Course VALUES ('Introduction to Political Philosophy', 'POLSCI 175');
INSERT INTO Course VALUES ('Nature of Freedom', 'POLSCI 180FS');
INSERT INTO Course VALUES ('Conflit, Collision and Cooperation', 'POLSCI 183FS');
INSERT INTO Course VALUES ('Introduction to Machine Learning', 'POLSCI 189FS');
INSERT INTO Course VALUES ('American Values, Inst, Culture', 'POLSCI 206');
INSERT INTO Course VALUES ('Ethnic Conflict', 'POLSCI 227');
INSERT INTO Course VALUES ('Institutions and Self Governance', 'POLSCI 229');
INSERT INTO Course VALUES ('Theory and Practice: People, Places and Policy Cases', 'POLSCI 240SA');
INSERT INTO Course VALUES ('Whose Democracy? Participation and Public Policy in the United States', 'POLSCI 241SA');
INSERT INTO Course VALUES ('Campaigns and Elections', 'POLSCI 242S');
INSERT INTO Course VALUES ('Politics and literature', 'POLSCI 268');
INSERT INTO Course VALUES ('The UN Security Council and World Peace: Hope or Fantasy?', 'POLSCI 290A');
INSERT INTO Course VALUES ('Political Economy of Financial Crisis', 'POLSCI 315');
INSERT INTO Course VALUES ('Global Corruption', 'POLSCI 317S');
INSERT INTO Course VALUES ('Prisoner''s Dilemma and Distributive Justice', 'POLSCI 331/ECON 361/PHIL 246');
INSERT INTO Course VALUES ('Marxism and Society', 'POLSCI 371/SOCIOL 339');
INSERT INTO Course VALUES ('Politics and Policy Practicum', 'POLSCI 494A');
INSERT INTO Course VALUES ('In the Age of Globalization', 'POLSCI 89S');
INSERT INTO Course VALUES ('Elementary Portuguese', 'PORTUGUE 101');
INSERT INTO Course VALUES ('Introduction to Psychology', 'PSY 101');
INSERT INTO Course VALUES ('Cognitive Psychology', 'PSY 102');
INSERT INTO Course VALUES ('Developmental Psychology', 'PSY 103');
INSERT INTO Course VALUES ('Social Psychology', 'PSY 104');
INSERT INTO Course VALUES ('Abnormal Psychology', 'PSY 105');
INSERT INTO Course VALUES ('Biological Psychology', 'PSY 106');
INSERT INTO Course VALUES ('Addiction: Brain/Indivdual/Society', 'PSY 190FS');
INSERT INTO Course VALUES ('Introduction to Statistical Methods in Psychology', 'PSY 201');
INSERT INTO Course VALUES ('Practicum', 'PSY 203');
INSERT INTO Course VALUES ('Health Psych/Behav Change', 'PSY 205');
INSERT INTO Course VALUES ('Alcohol: Brain/Indiv/Soc', 'PSY 206');
INSERT INTO Course VALUES ('Forensic Psychology', 'PSY 212');
INSERT INTO Course VALUES ('Psychology of Gender', 'PSY 220');
INSERT INTO Course VALUES ('Personality Psychology', 'PSY 221');
INSERT INTO Course VALUES ('Social Identities', 'PSY 223');
INSERT INTO Course VALUES ('Sex and Gender, Nature and Nurture', 'PSY 226');
INSERT INTO Course VALUES ('Social Development', 'PSY 237');
INSERT INTO Course VALUES ('Adolescence', 'PSY 239');
INSERT INTO Course VALUES ('Educational Psychology', 'PSY 240');
INSERT INTO Course VALUES ('Myths and Mysteries of Memory', 'PSY 250');
INSERT INTO Course VALUES ('Human Cognitive Evolution', 'PSY 255');
INSERT INTO Course VALUES ('Neuroethics', 'PSY 278');
INSERT INTO Course VALUES ('Research Methods (Psychopathology and Psychotherapy)', 'PSY 310');
INSERT INTO Course VALUES ('Develop Your Life', 'PSY 390');
INSERT INTO Course VALUES ('Psychology of Consumers', 'PSY 425');
INSERT INTO Course VALUES ('Social Psychology of Business', 'PSY 426');
INSERT INTO Course VALUES ('Psychology of Mindfulness', 'PSY 610S');
INSERT INTO Course VALUES ('Everyday Cognition', 'PSY 668S');
INSERT INTO Course VALUES ('Empathy and Identity', 'PSY 89S');
INSERT INTO Course VALUES ('Introduction to Policy Analysis', 'PUBPOL 155');
INSERT INTO Course VALUES ('Introduction to US health care system', 'PUBPOL 165');
INSERT INTO Course VALUES ('Public Speaking', 'PUBPOL 182');
INSERT INTO Course VALUES ('Leadership & Civic Engag', 'PUBPOL 190FS');
INSERT INTO Course VALUES ('Political Philosophy of Globalization', 'PUBPOL 204A');
INSERT INTO Course VALUES ('Global Russia', 'PUBPOL 223');
INSERT INTO Course VALUES ('Law, Ethics, and Responsibility', 'PUBPOL 250FS');
INSERT INTO Course VALUES ('Border Crossing: value conflicts, public life, and leadership', 'PUBPOL 263');
INSERT INTO Course VALUES ('Environmental History', 'PUBPOL 278');
INSERT INTO Course VALUES ('Cold War', 'PUBPOL 290');
INSERT INTO Course VALUES ('Ethics in an Unjust World', 'PUBPOL 290');
INSERT INTO Course VALUES ('Sexuality and Law', 'PUBPOL 290S');
INSERT INTO Course VALUES ('Food, Environmen and development', 'PUBPOL 290S');
INSERT INTO Course VALUES ('Relations Between Industrialized and Developing Nations', 'PUBPOL 295S');
INSERT INTO Course VALUES ('Political Analysis for Public Policy-Making', 'PUBPOL 301');
INSERT INTO Course VALUES ('Policy Choice as Value Conflict', 'PUBPOL 302');
INSERT INTO Course VALUES ('Microeconomic Policy Tools', 'PUBPOL 303');
INSERT INTO Course VALUES ('Economics of the Public Sector', 'PUBPOL 304');
INSERT INTO Course VALUES ('Business and Human Rights', 'PUBPOL 311');
INSERT INTO Course VALUES ('Economic and political history of European Union', 'PUBPOL 351A');
INSERT INTO Course VALUES ('News as Moral Battleground', 'PUBPOL 371');
INSERT INTO Course VALUES ('Food Studies: Interdiscinplinary Approach', 'PUBPOL 390/ECON 390');
INSERT INTO Course VALUES ('Intellectual Property and Innovation', 'PUBPOL 425');
INSERT INTO Course VALUES ('PUBPOL Honor Seminar (Seminar)', 'PUBPOL 495S');
INSERT INTO Course VALUES ('PUBPOL Honor Seminar', 'PUBPOL 496S');
INSERT INTO Course VALUES ('Philanthropy, practice of giving', 'PUBPOL 560');
INSERT INTO Course VALUES ('Economic Growth and development policy', 'PUBPOL 598');
INSERT INTO Course VALUES ('Buddhism and Sexuality', 'REL 328/AMES 286');
INSERT INTO Course VALUES ('Linguistics/Human Rights', 'ROMST 190FS');
INSERT INTO Course VALUES ('Topics in Romance Studies-Linguistics/Human Rights', 'ROMST 190FS');
INSERT INTO Course VALUES ('Intermediate Russian', 'RUSSIAN 204');
INSERT INTO Course VALUES ('Sociological Inquiry', 'SOCIOL 110');
INSERT INTO Course VALUES ('Causes of crime', 'SOCIOL 220');
INSERT INTO Course VALUES ('Gender, Work, and Organization', 'SOCIOL 229');
INSERT INTO Course VALUES ('Medical Sociology', 'SOCIOL 250');
INSERT INTO Course VALUES ('Who gets sick and why?', 'SOCIOL 290');
INSERT INTO Course VALUES ('Technology and Organizational Environments', 'SOCIOL 344');
INSERT INTO Course VALUES ('Nations, Regions, and Global Economy', 'SOCIOL 345');
INSERT INTO Course VALUES ('Getting Rich', 'SOCIOL 354');
INSERT INTO Course VALUES ('Organizations/Management', 'SOCIOL 355');
INSERT INTO Course VALUES ('Elementary Spanish II', 'SPANISH 102');
INSERT INTO Course VALUES ('Cognition, Identity, and Linguistic Human RIghts', 'SPANISH 190FS');
INSERT INTO Course VALUES ('Intermediate Spanish', 'SPANISH 203');
INSERT INTO Course VALUES ('Advanced Intermediate Spanish', 'SPANISH 204');
INSERT INTO Course VALUES ('Advanced Spanish Writing', 'SPANISH 301');
INSERT INTO Course VALUES ('Data Analysis and Statistical Inference', 'STA 101');
INSERT INTO Course VALUES ('Biostatistics', 'STA 102');
INSERT INTO Course VALUES ('Introduction to Statistical Modeling', 'STA 110FS');
INSERT INTO Course VALUES ('Introductory Special Topics in Statistics', 'STA 110FS');
INSERT INTO Course VALUES ('Probability and Statistical Inference', 'STA 111');
INSERT INTO Course VALUES ('Better Living Through Data Science', 'STA 112FS');
INSERT INTO Course VALUES ('Regression Analysis', 'STA 210');
INSERT INTO Course VALUES ('Probability', 'STA 230/MATH 230');
INSERT INTO Course VALUES ('Statistics', 'STA 250/MATH 342');
INSERT INTO Course VALUES ('Design and Analysis of Causal Studies', 'STA 320');
INSERT INTO Course VALUES ('Survey Statistics', 'STA 321');
INSERT INTO Course VALUES ('Study Design', 'STA 322');
INSERT INTO Course VALUES ('Statistical Computing', 'STA 323');
INSERT INTO Course VALUES ('Introduction to Statistical Decision Analysis', 'STA 340');
INSERT INTO Course VALUES ('Bayesian Inference and Modern Statistical Methods', 'STA 360');
INSERT INTO Course VALUES ('Case Studies', 'STA 440');
INSERT INTO Course VALUES ('Statistical Consulting', 'STA 470');
INSERT INTO Course VALUES ('Predictive Modelling', 'STA 521');
INSERT INTO Course VALUES ('Theory of Inference', 'STA 532');
INSERT INTO Course VALUES ('Advanced Machine Learning', 'STA 571');
INSERT INTO Course VALUES ('Stochastic Processes', 'STA 621');
INSERT INTO Course VALUES ('Statistical Computation', 'STA 663');
INSERT INTO Course VALUES ('The Theater Today', 'THEATRST 115');
INSERT INTO Course VALUES ('Acting', 'THEATRST 145S');
INSERT INTO Course VALUES ('American Musicals', 'THEATRST 210');
INSERT INTO Course VALUES ('Shakespeare: Shakespeare on Love', 'THEATRST 222');
INSERT INTO Course VALUES ('Asian American Theatre', 'THEATRST 232');
INSERT INTO Course VALUES ('Voice & Speech', 'THEATRST 248S');
INSERT INTO Course VALUES ('America Dreams/American Movies', 'THEATRST 272');
INSERT INTO Course VALUES ('Audition Technique', 'THEATRST 290S');
INSERT INTO Course VALUES ('Non-profit Cultural Institutions', 'THEATRST 310S');
INSERT INTO Course VALUES ('The Actress', 'THEATRST 323');
INSERT INTO Course VALUES ('Elementary Tibetan', 'TIBETAN 101');
INSERT INTO Course VALUES ('Digital Photography', 'VMS 209');
INSERT INTO Course VALUES ('Modern Chinese Cinemas: Master Filmmakers', 'VMS 235');
INSERT INTO Course VALUES ('Media History: Old and New', 'VMS 266');
INSERT INTO Course VALUES ('Motion Design', 'VMS 281S');
INSERT INTO Course VALUES ('Magazine Journalism', 'VMS 306S');
INSERT INTO Course VALUES ('Advanced Visual Practice', 'VMS 497S/ARTSVIS 497S');
INSERT INTO Course VALUES ('Ongoing Moments', 'VMS 630');
INSERT INTO Course VALUES ('Mapping and Modeling Early Venice', 'VMS 89S');
INSERT INTO Course VALUES ('Real Work And Dream Jobs', 'WOMENST 190');
INSERT INTO Course VALUES ('Study of Sexualities', 'WOMENST 202S');
INSERT INTO Course VALUES ('Interpretin Bodies', 'WOMENST 363S');
INSERT INTO Course VALUES ('Politics of Sexuality', 'WOMENST 386S');
INSERT INTO Course VALUES ('Girls Go Global', 'WOMENST 89S');
INSERT INTO Course VALUES ('2012: Myth of the Maya', 'WRITING 101');
INSERT INTO Course VALUES ('African Lit and Ecological', 'WRITING 101');
INSERT INTO Course VALUES ('American Wild', 'WRITING 101');
INSERT INTO Course VALUES ('Can Chimps Have Culture', 'WRITING 101');
INSERT INTO Course VALUES ('Consuming African Cities', 'WRITING 101');
INSERT INTO Course VALUES ('Controlling Nature', 'WRITING 101');
INSERT INTO Course VALUES ('Courtroom Body and Law', 'WRITING 101');
INSERT INTO Course VALUES ('Debt Race and Power', 'WRITING 101');
INSERT INTO Course VALUES ('Decoding Disney', 'WRITING 101');
INSERT INTO Course VALUES ('Deportation Nation', 'WRITING 101');
INSERT INTO Course VALUES ('Emerson''s Ethics', 'WRITING 101');
INSERT INTO Course VALUES ('Feminism, Capitalism and Social Changes', 'WRITING 101');
INSERT INTO Course VALUES ('Grassroots activism', 'WRITING 101');
INSERT INTO Course VALUES ('Health, Medicine, and Culture', 'WRITING 101');
INSERT INTO Course VALUES ('History of Policing', 'WRITING 101');
INSERT INTO Course VALUES ('How to Make Mistakes', 'WRITING 101');
INSERT INTO Course VALUES ('Illness narratives', 'WRITING 101');
INSERT INTO Course VALUES ('Intellectuals: Who are They?', 'WRITING 101');
INSERT INTO Course VALUES ('Islam is not Isis', 'WRITING 101');
INSERT INTO Course VALUES ('Land of Free', 'WRITING 101');
INSERT INTO Course VALUES ('Land of the free-Racism and American Legal system', 'WRITING 101');
INSERT INTO Course VALUES ('Language Diversity in the United States', 'WRITING 101');
INSERT INTO Course VALUES ('Law and Literature', 'WRITING 101');
INSERT INTO Course VALUES ('Madness in Literature', 'WRITING 101');
INSERT INTO Course VALUES ('Making the familiar strange', 'WRITING 101');
INSERT INTO Course VALUES ('Memory and Truama in Latin American Film', 'WRITING 101');
INSERT INTO Course VALUES ('Monkey Mindreading', 'WRITING 101');
INSERT INTO Course VALUES ('Neanderthal Tales', 'WRITING 101');
INSERT INTO Course VALUES ('Word Sound and Music', 'WRITING 101');
INSERT INTO Course VALUES ('Public History Writing', 'WRITING 101');
INSERT INTO Course VALUES ('Race, Debt, and Power', 'WRITING 101');
INSERT INTO Course VALUES ('Radical Politics', 'WRITING 101');
INSERT INTO Course VALUES ('Rationalization and Confabulation', 'WRITING 101');
INSERT INTO Course VALUES ('Ritual and Performaces', 'WRITING 101');
INSERT INTO Course VALUES ('Science Fails', 'WRITING 101');
INSERT INTO Course VALUES ('Science of Food Choice', 'WRITING 101');
INSERT INTO Course VALUES ('Social Movements in the Americas', 'WRITING 101');
INSERT INTO Course VALUES ('Sound, Art and Abstraction', 'WRITING 101');
INSERT INTO Course VALUES ('Stranger than Fiction', 'WRITING 101');
INSERT INTO Course VALUES ('Students as Activists', 'WRITING 101');
INSERT INTO Course VALUES ('The Problem of the Color Line', 'WRITING 101');
INSERT INTO Course VALUES ('Topicbehavioral Econ-Animal Welfare', 'WRITING 101');
INSERT INTO Course VALUES ('Urban Wildlife Conservation', 'WRITING 101');
INSERT INTO Course VALUES ('Writing About Social Movements', 'WRITING 101');
INSERT INTO Course VALUES ('Neuroscience & The Law', 'WRITING 101');
INSERT INTO Course VALUES ('Coming of Age at Duke', 'WRITING 101');
INSERT INTO Course VALUES ('Digital Rhetoric and Social Media Discourse', 'WRITING 270');
