INSERT INTO Professor VALUES (	'Fryar C'	);
INSERT INTO Professor VALUES (	'C. Royal'	);
INSERT INTO Professor VALUES (	'Charmaine Royale'	);
INSERT INTO Professor VALUES (	'Thomas DeFrantz'	);
INSERT INTO Professor VALUES (	'Crichlow, M'	);
INSERT INTO Professor VALUES (	'Piot C'	);
INSERT INTO Professor VALUES (	'Ning Zhang'	);
INSERT INTO Professor VALUES (	'Hwansoo Kim'	);
INSERT INTO Professor VALUES (	'Kim, H.'	);
INSERT INTO Professor VALUES (	'Kim H, Kwon N'	);
INSERT INTO Professor VALUES (	'Carlos Rojas'	);
INSERT INTO Professor VALUES (	'Xuenan C'	);
INSERT INTO Professor VALUES (	'Xuenan Cao'	);
INSERT INTO Professor VALUES (	'Mbaye Lo'	);
INSERT INTO Professor VALUES (	'Kramer J'	);
INSERT INTO Professor VALUES (	'Partner S'	);
INSERT INTO Professor VALUES (	'Kim H'	);
INSERT INTO Professor VALUES (	'Kadivar M'	);
INSERT INTO Professor VALUES (	'Dwayne Dixon'	);
INSERT INTO Professor VALUES (	'Dixon D'	);
INSERT INTO Professor VALUES (	'Chow E'	);
INSERT INTO Professor VALUES (	'Chow, E'	);
INSERT INTO Professor VALUES (	'Rojas C'	);
INSERT INTO Professor VALUES (	'Liu K'	);
INSERT INTO Professor VALUES (	'KANG LIU'	);
INSERT INTO Professor VALUES (	'Leo Ching'	);
INSERT INTO Professor VALUES (	'Cheehyung Kim'	);
INSERT INTO Professor VALUES (	'Kim, Cheehyung'	);
INSERT INTO Professor VALUES (	'Guo-Juin Hong'	);
INSERT INTO Professor VALUES (	'Hong G'	);
INSERT INTO Professor VALUES (	'Hong GJ'	);
INSERT INTO Professor VALUES (	'Hwansoo Kim and Aimee Nayoung Kim'	);
INSERT INTO Professor VALUES (	'Mottahadeh, N'	);
INSERT INTO Professor VALUES (	'Elizabeth L'	);
INSERT INTO Professor VALUES (	'Karen Price'	);
INSERT INTO Professor VALUES (	'Herbert D'	);
INSERT INTO Professor VALUES (	'Metzger, S'	);
INSERT INTO Professor VALUES (	'Kathleen Dowdey'	);
INSERT INTO Professor VALUES (	'Haverkamp J'	);
INSERT INTO Professor VALUES (	'Haverkamp'	);
INSERT INTO Professor VALUES (	'Gary Hawkins'	);
INSERT INTO Professor VALUES (	'Kaul S'	);
INSERT INTO Professor VALUES (	'Shambhavi Kaul'	);
INSERT INTO Professor VALUES (	'Haverkamp,James R'	);
INSERT INTO Professor VALUES (	'Bill Seaman & John Supko'	);
INSERT INTO Professor VALUES (	'Gustavo Furtado'	);
INSERT INTO Professor VALUES (	'Douglas Herbert'	);
INSERT INTO Professor VALUES (	'Douglas Hubert'	);
INSERT INTO Professor VALUES (	'Jim Haverkamp'	);
INSERT INTO Professor VALUES (	'Andrew Weinstein '	);
INSERT INTO Professor VALUES (	'Andrew Weinstein'	);
INSERT INTO Professor VALUES (	'Edward Triplett'	);
INSERT INTO Professor VALUES (	'Antonaccio'	);
INSERT INTO Professor VALUES (	'Antonaccio C'	);
INSERT INTO Professor VALUES (	'mazurek'	);
INSERT INTO Professor VALUES (	'C. Bruzelius'	);
INSERT INTO Professor VALUES (	'Gennifer Weisenfield'	);
INSERT INTO Professor VALUES (	'Weisenfeld'	);
INSERT INTO Professor VALUES (	'K. Lanzoni'	);
INSERT INTO Professor VALUES (	'Galletti S'	);
INSERT INTO Professor VALUES (	'Narkin E'	);
INSERT INTO Professor VALUES (	'Dillon, J'	);
INSERT INTO Professor VALUES (	'Kachurin,. P'	);
INSERT INTO Professor VALUES (	'Pamela Kachurin'	);
INSERT INTO Professor VALUES (	'Antliff M'	);
INSERT INTO Professor VALUES (	'Patricia Leighten'	);
INSERT INTO Professor VALUES (	'McCarty L'	);
INSERT INTO Professor VALUES (	'Bogaert A'	);
INSERT INTO Professor VALUES (	'William Thomas'	);
INSERT INTO Professor VALUES (	'William P Thomas'	);
INSERT INTO Professor VALUES (	'Antonio Bogaert'	);
INSERT INTO Professor VALUES (	'Bill Fick'	);
INSERT INTO Professor VALUES (	'Fick W'	);
INSERT INTO Professor VALUES (	'Salvatella De Prada'	);
INSERT INTO Professor VALUES (	'Lercari N'	);
INSERT INTO Professor VALUES (	'Herrera J'	);
INSERT INTO Professor VALUES (	'Bogaert'	);
INSERT INTO Professor VALUES (	'Michael Faber'	);
INSERT INTO Professor VALUES (	'Kipervaser A'	);
INSERT INTO Professor VALUES (	'Susie Post-Rust'	);
INSERT INTO Professor VALUES (	'Burns F'	);
INSERT INTO Professor VALUES (	'Noland W'	);
INSERT INTO Professor VALUES (	'Seaman W'	);
INSERT INTO Professor VALUES (	'Aaron Kutnick'	);
INSERT INTO Professor VALUES (	'Eric Spana and Amy Schmidt '	);
INSERT INTO Professor VALUES (	'Buchler N'	);
INSERT INTO Professor VALUES (	'Nick Buchler, Alison Hill'	);
INSERT INTO Professor VALUES (	'Alison Hill'	);
INSERT INTO Professor VALUES (	'John Willis'	);
INSERT INTO Professor VALUES (	'John H Willis'	);
INSERT INTO Professor VALUES (	'Willis J'	);
INSERT INTO Professor VALUES (	'Amy Bejsovec and Mark Rausher'	);
INSERT INTO Professor VALUES (	'Mohamad N'	);
INSERT INTO Professor VALUES (	'Julie Reynold '	);
INSERT INTO Professor VALUES (	'Hasse, Steven'	);
INSERT INTO Professor VALUES (	'Nina Sherwood and peilin '	);
INSERT INTO Professor VALUES (	'McShea D and Brandon R'	);
INSERT INTO Professor VALUES (	'Spans E'	);
INSERT INTO Professor VALUES (	'Johnson S'	);
INSERT INTO Professor VALUES (	'Sheila Patek '	);
INSERT INTO Professor VALUES (	'Buchler N, Hill  A'	);
INSERT INTO Professor VALUES (	'Hill K'	);
INSERT INTO Professor VALUES (	'Magwene P'	);
INSERT INTO Professor VALUES (	'Bejsovec A'	);
INSERT INTO Professor VALUES (	'Sherwood N'	);
INSERT INTO Professor VALUES (	'Donohue K'	);
INSERT INTO Professor VALUES (	'Department'	);
INSERT INTO Professor VALUES (	'Brian Coggins'	);
INSERT INTO Professor VALUES (	'Coggins, Brian'	);
INSERT INTO Professor VALUES (	'Coggins B'	);
INSERT INTO Professor VALUES (	'Jory W'	);
INSERT INTO Professor VALUES (	'Schmitt D, Wray G'	);
INSERT INTO Professor VALUES (	'Hill A'	);
INSERT INTO Professor VALUES (	'Alex. Glass'	);
INSERT INTO Professor VALUES (	'Buchler, Nicolas'	);
INSERT INTO Professor VALUES (	'David McClay; Dr. Hasse'	);
INSERT INTO Professor VALUES (	'Haase S'	);
INSERT INTO Professor VALUES (	'Siedow and McClay'	);
INSERT INTO Professor VALUES (	'Haase & McClay'	);
INSERT INTO Professor VALUES (	'Kiehart, D; Hill, A; Buchler, N'	);
INSERT INTO Professor VALUES (	'Schultz T'	);
INSERT INTO Professor VALUES (	'Prof Willis'	);
INSERT INTO Professor VALUES (	'Noor M'	);
INSERT INTO Professor VALUES (	'Willis'	);
INSERT INTO Professor VALUES (	'Noor, Mohammed'	);
INSERT INTO Professor VALUES (	'Sherwood D / Spana E'	);
INSERT INTO Professor VALUES (	'Sherwood D, Spana E'	);
INSERT INTO Professor VALUES (	'Sherwood, D.'	);
INSERT INTO Professor VALUES (	'Noor, J'	);
INSERT INTO Professor VALUES (	'amy'	);
INSERT INTO Professor VALUES (	'Craig Henriquez'	);
INSERT INTO Professor VALUES (	'Wallace C'	);
INSERT INTO Professor VALUES (	'Lynch & Mulvey'	);
INSERT INTO Professor VALUES (	'Chelsea Salinas'	);
INSERT INTO Professor VALUES (	'Lingchong You'	);
INSERT INTO Professor VALUES (	'You L'	);
INSERT INTO Professor VALUES (	'Saterbak A'	);
INSERT INTO Professor VALUES (	'Farsui S'	);
INSERT INTO Professor VALUES (	'Yiyang Gong'	);
INSERT INTO Professor VALUES (	'Brent Hoffman and Jason luck '	);
INSERT INTO Professor VALUES (	'Kathryn nightingale '	);
INSERT INTO Professor VALUES (	'Malkin R'	);
INSERT INTO Professor VALUES (	'Henriquez, C'	);
INSERT INTO Professor VALUES (	'Celinas'	);
INSERT INTO Professor VALUES (	'Dr. Neu'	);
INSERT INTO Professor VALUES (	'Wanda Neu'	);
INSERT INTO Professor VALUES (	'Tomasi C'	);
INSERT INTO Professor VALUES (	'Schaad D'	);
INSERT INTO Professor VALUES (	'Emma Jakoi'	);
INSERT INTO Professor VALUES (	'Emma Jakoi and Jennifer Carbrey'	);
INSERT INTO Professor VALUES (	'Multiple'	);
INSERT INTO Professor VALUES (	'C. Roy'	);
INSERT INTO Professor VALUES (	'Christopher P. Roy,  Richard A MacPhail'	);
INSERT INTO Professor VALUES (	'Roy C'	);
INSERT INTO Professor VALUES (	'Woerner T'	);
INSERT INTO Professor VALUES (	'Richard MacPhail'	);
INSERT INTO Professor VALUES (	'Canelas D'	);
INSERT INTO Professor VALUES (	'Wang Qiu'	);
INSERT INTO Professor VALUES (	'Dorian Canelas '	);
INSERT INTO Professor VALUES (	'Steven Baldwin'	);
INSERT INTO Professor VALUES (	'Hargrove A'	);
INSERT INTO Professor VALUES (	'Qiu Wang'	);
INSERT INTO Professor VALUES (	'Wang Q'	);
INSERT INTO Professor VALUES (	'Canelas and Hargroves'	);
INSERT INTO Professor VALUES (	'Baldwin S'	);
INSERT INTO Professor VALUES (	'Wang, Q'	);
INSERT INTO Professor VALUES (	'Widenhoefer'	);
INSERT INTO Professor VALUES (	'Widenhoefer R'	);
INSERT INTO Professor VALUES (	'Balwin'	);
INSERT INTO Professor VALUES (	'Crumbliss, A'	);
INSERT INTO Professor VALUES (	'MacPhail'	);
INSERT INTO Professor VALUES (	'Dorian Canelas'	);
INSERT INTO Professor VALUES (	'Bonk'	);
INSERT INTO Professor VALUES (	'Dewey McCafferty'	);
INSERT INTO Professor VALUES (	'McCarthy D'	);
INSERT INTO Professor VALUES (	'Christopher Roy'	);
INSERT INTO Professor VALUES (	'R. Macphail'	);
INSERT INTO Professor VALUES (	'Stephen Craig'	);
INSERT INTO Professor VALUES (	'Jie Liu'	);
INSERT INTO Professor VALUES (	'Chris Roy and McPhail'	);
INSERT INTO Professor VALUES (	'He T'	);
INSERT INTO Professor VALUES (	'Dan Wang'	);
INSERT INTO Professor VALUES (	'Liu, Y'	);
INSERT INTO Professor VALUES (	'Yan Liu'	);
INSERT INTO Professor VALUES (	'Hsieh, C'	);
INSERT INTO Professor VALUES (	'Chao Yu-wen'	);
INSERT INTO Professor VALUES (	'Cai J'	);
INSERT INTO Professor VALUES (	'Eileen Chow'	);
INSERT INTO Professor VALUES (	'Birong Wang'	);
INSERT INTO Professor VALUES (	'Liu Kang'	);
INSERT INTO Professor VALUES (	'Wang'	);
INSERT INTO Professor VALUES (	'Elieen Chow'	);
INSERT INTO Professor VALUES (	'Liu K.'	);
INSERT INTO Professor VALUES (	'Kang L'	);
INSERT INTO Professor VALUES (	'Lang liu'	);
INSERT INTO Professor VALUES (	'Michael Ferejohn'	);
INSERT INTO Professor VALUES (	'Forbes J'	);
INSERT INTO Professor VALUES (	'Susuan Rodger'	);
INSERT INTO Professor VALUES (	'Duvall D'	);
INSERT INTO Professor VALUES (	'Susan H Rodger'	);
INSERT INTO Professor VALUES (	'Astrachan O'	);
INSERT INTO Professor VALUES (	'Duvall'	);
INSERT INTO Professor VALUES (	'Owen'	);
INSERT INTO Professor VALUES (	'Owen L. Astrachan'	);
INSERT INTO Professor VALUES (	'Rodger, S'	);
INSERT INTO Professor VALUES (	'S Rodger'	);
INSERT INTO Professor VALUES (	'Susan Rodger'	);
INSERT INTO Professor VALUES (	'Susan Roger'	);
INSERT INTO Professor VALUES (	'Rodger S'	);
INSERT INTO Professor VALUES (	'Astracan O'	);
INSERT INTO Professor VALUES (	'Duvall R'	);
INSERT INTO Professor VALUES (	'Rodgers S'	);
INSERT INTO Professor VALUES (	'Susan Rodger Fall 2014'	);
INSERT INTO Professor VALUES (	'Jeff Forbes'	);
INSERT INTO Professor VALUES (	'Salman Azhar'	);
INSERT INTO Professor VALUES (	'Sam Azhar'	);
INSERT INTO Professor VALUES (	'Mason, M.'	);
INSERT INTO Professor VALUES (	'Azar Salman'	);
INSERT INTO Professor VALUES (	'Azhar S'	);
INSERT INTO Professor VALUES (	'J. Forbes'	);
INSERT INTO Professor VALUES (	'Jeffery Forbes'	);
INSERT INTO Professor VALUES (	'Jeffrey Forbes'	);
INSERT INTO Professor VALUES (	'Peck T'	);
INSERT INTO Professor VALUES (	'Ashwin M.'	);
INSERT INTO Professor VALUES (	'Ashwin, Dennis'	);
INSERT INTO Professor VALUES (	'Tripathy, C.'	);
INSERT INTO Professor VALUES (	'Carlo Tomasi'	);
INSERT INTO Professor VALUES (	'Donald'	);
INSERT INTO Professor VALUES (	'Bruce Donald'	);
INSERT INTO Professor VALUES (	'Kamesh Munagala'	);
INSERT INTO Professor VALUES (	'Benjamin Lee'	);
INSERT INTO Professor VALUES (	'D. Sorin'	);
INSERT INTO Professor VALUES (	'Daniel Sorin'	);
INSERT INTO Professor VALUES (	'Sorin'	);
INSERT INTO Professor VALUES (	'Sorin D'	);
INSERT INTO Professor VALUES (	'Tyler Blestch'	);
INSERT INTO Professor VALUES (	'Bletsch T'	);
INSERT INTO Professor VALUES (	'Hartemink A'	);
INSERT INTO Professor VALUES (	'Hartemink Alexander'	);
INSERT INTO Professor VALUES (	'Parr'	);
INSERT INTO Professor VALUES (	'Ron Parr'	);
INSERT INTO Professor VALUES (	'Bruce Maggs'	);
INSERT INTO Professor VALUES (	'S. Babu'	);
INSERT INTO Professor VALUES (	'Owen A'	);
INSERT INTO Professor VALUES (	'Chris Tralie'	);
INSERT INTO Professor VALUES (	'Maggs, B'	);
INSERT INTO Professor VALUES (	'Robert Duvall'	);
INSERT INTO Professor VALUES (	'Chase J'	);
INSERT INTO Professor VALUES (	'Jeffery chase'	);
INSERT INTO Professor VALUES (	'Landon Cox'	);
INSERT INTO Professor VALUES (	'Jeff Chase'	);
INSERT INTO Professor VALUES (	'Cox, L'	);
INSERT INTO Professor VALUES (	'Jeffrey Chase'	);
INSERT INTO Professor VALUES (	'Yang, J'	);
INSERT INTO Professor VALUES (	'Jun Yang'	);
INSERT INTO Professor VALUES (	'Yang J'	);
INSERT INTO Professor VALUES (	'Yang Jun'	);
INSERT INTO Professor VALUES (	'D'	);
INSERT INTO Professor VALUES (	'Debmalya panigrahi'	);
INSERT INTO Professor VALUES (	'Munagala'	);
INSERT INTO Professor VALUES (	'Rong Ge'	);
INSERT INTO Professor VALUES (	'Munagala K'	);
INSERT INTO Professor VALUES (	'Nick Gross'	);
INSERT INTO Professor VALUES (	'Benson T'	);
INSERT INTO Professor VALUES (	'Yang Xiaowei'	);
INSERT INTO Professor VALUES (	'Lopez A'	);
INSERT INTO Professor VALUES (	'Xiaowei Yang'	);
INSERT INTO Professor VALUES (	'Xiaowei Yang & Theo Benson'	);
INSERT INTO Professor VALUES (	'Yang, X'	);
INSERT INTO Professor VALUES (	'Lucic R'	);
INSERT INTO Professor VALUES (	'P. Bendich, C. Rudin, A. Gelfand, L. carin'	);
INSERT INTO Professor VALUES (	'Maggs B'	);
INSERT INTO Professor VALUES (	'Babu S'	);
INSERT INTO Professor VALUES (	'Hilton A'	);
INSERT INTO Professor VALUES (	'Rudin C'	);
INSERT INTO Professor VALUES (	'Tralie C'	);
INSERT INTO Professor VALUES (	'Susan Rodgers'	);
INSERT INTO Professor VALUES (	'Owen Astrachan, Jennifer Groh'	);
INSERT INTO Professor VALUES (	'Owen Astrachan '	);
INSERT INTO Professor VALUES (	'Owen '	);
INSERT INTO Professor VALUES (	'Owen Astrachan'	);
INSERT INTO Professor VALUES (	'Tomasi C.'	);
INSERT INTO Professor VALUES (	'Danial Sorin'	);
INSERT INTO Professor VALUES (	'A Hartemink'	);
INSERT INTO Professor VALUES (	'Duvall '	);
INSERT INTO Professor VALUES (	'Chase J.'	);
INSERT INTO Professor VALUES (	'Yang J. '	);
INSERT INTO Professor VALUES (	'Sudeepa Roy'	);
INSERT INTO Professor VALUES (	'Ge R'	);
INSERT INTO Professor VALUES (	'Debmalya Panigraphi'	);
INSERT INTO Professor VALUES (	'Panigrahi Debmalya'	);
INSERT INTO Professor VALUES (	'Cynthia Rundin'	);
INSERT INTO Professor VALUES (	'Kritin Martinez'	);
INSERT INTO Professor VALUES (	'SALMEN AZHAR'	);
INSERT INTO Professor VALUES (	'Jerf F'	);
INSERT INTO Professor VALUES (	'Astrachan Owen L'	);
INSERT INTO Professor VALUES (	'Forbes'	);
INSERT INTO Professor VALUES (	'Ola'	);
INSERT INTO Professor VALUES (	' Ashwin Machanavajjhala'	);
INSERT INTO Professor VALUES (	'Ashwin'	);
INSERT INTO Professor VALUES (	'Ashwin Machanavajjhala '	);
INSERT INTO Professor VALUES (	'Machanavajjhala A'	);
INSERT INTO Professor VALUES (	'Donald B'	);
INSERT INTO Professor VALUES (	'Carlo T'	);
INSERT INTO Professor VALUES (	'Lee B'	);
INSERT INTO Professor VALUES (	'Ronald Parr'	);
INSERT INTO Professor VALUES (	'Hauser K'	);
INSERT INTO Professor VALUES (	'Cynthia Rudin'	);
INSERT INTO Professor VALUES (	'Owen Astrachan + Landon Cox'	);
INSERT INTO Professor VALUES (	'JUN Y'	);
INSERT INTO Professor VALUES (	'Kamesh Munagal'	);
INSERT INTO Professor VALUES (	'Panigrahi '	);
INSERT INTO Professor VALUES (	'Debmalya Panigrahi '	);
INSERT INTO Professor VALUES (	'Panigrahi D'	);
INSERT INTO Professor VALUES (	'Roy S'	);
INSERT INTO Professor VALUES (	'Katya Wesolowski'	);
INSERT INTO Professor VALUES (	'Orin Star'	);
INSERT INTO Professor VALUES (	'Starn O'	);
INSERT INTO Professor VALUES (	'Starn, O'	);
INSERT INTO Professor VALUES (	'Ingrid Byerly'	);
INSERT INTO Professor VALUES (	'O barr'	);
INSERT INTO Professor VALUES (	'O Barr W'	);
INSERT INTO Professor VALUES (	'Ingrid B'	);
INSERT INTO Professor VALUES (	'Richard Collier '	);
INSERT INTO Professor VALUES (	'Thorneburg A'	);
INSERT INTO Professor VALUES (	'Allison'	);
INSERT INTO Professor VALUES (	'Sobel-Read, K'	);
INSERT INTO Professor VALUES (	'Thompson C'	);
INSERT INTO Professor VALUES (	'Ralph Litzinger'	);
INSERT INTO Professor VALUES (	'Netta'	);
INSERT INTO Professor VALUES (	'Christine Folch'	);
INSERT INTO Professor VALUES (	'Diane Nelson'	);
INSERT INTO Professor VALUES (	'Makhulu, A'	);
INSERT INTO Professor VALUES (	'Christian Forch'	);
INSERT INTO Professor VALUES (	'Shah'	);
INSERT INTO Professor VALUES (	'Walters, T'	);
INSERT INTO Professor VALUES (	'Walters T'	);
INSERT INTO Professor VALUES (	'Johnson, M'	);
INSERT INTO Professor VALUES (	'Nina Wheeler'	);
INSERT INTO Professor VALUES (	'Marrone, N'	);
INSERT INTO Professor VALUES (	'Knight Walker, J'	);
INSERT INTO Professor VALUES (	'Wheeler, N'	);
INSERT INTO Professor VALUES (	'Wheeler'	);
INSERT INTO Professor VALUES (	'Johnson M'	);
INSERT INTO Professor VALUES (	'Ava Vinesett'	);
INSERT INTO Professor VALUES (	'Katya Waslowski'	);
INSERT INTO Professor VALUES (	'Anna Kipervaser'	);
INSERT INTO Professor VALUES (	'William (Bill) Bamberger'	);
INSERT INTO Professor VALUES (	'Gutfason M'	);
INSERT INTO Professor VALUES (	'Michael Gustafson'	);
INSERT INTO Professor VALUES (	'Steven Cummer'	);
INSERT INTO Professor VALUES (	'Ybarra, Dr.G'	);
INSERT INTO Professor VALUES (	'M. Gustafson'	);
INSERT INTO Professor VALUES (	'Ybarra'	);
INSERT INTO Professor VALUES (	'Hisham Massoud'	);
INSERT INTO Professor VALUES (	'Aaron Franklin'	);
INSERT INTO Professor VALUES (	'Benjamine Lee'	);
INSERT INTO Professor VALUES (	'Lebeck A'	);
INSERT INTO Professor VALUES (	'Ben Lee'	);
INSERT INTO Professor VALUES (	'Steven C'	);
INSERT INTO Professor VALUES (	'Cummer'	);
INSERT INTO Professor VALUES (	'Kip Coolney'	);
INSERT INTO Professor VALUES (	'Dr. Collins'	);
INSERT INTO Professor VALUES (	'Lisa Huettel'	);
INSERT INTO Professor VALUES (	'Chris Dwyer'	);
INSERT INTO Professor VALUES (	'Dwyer'	);
INSERT INTO Professor VALUES (	'Li, H'	);
INSERT INTO Professor VALUES (	'Yiran Chen'	);
INSERT INTO Professor VALUES (	'Loren Nolte'	);
INSERT INTO Professor VALUES (	'Nolte'	);
INSERT INTO Professor VALUES (	'Andrew Hilton'	);
INSERT INTO Professor VALUES (	'John Board'	);
INSERT INTO Professor VALUES (	'Hilton, A'	);
INSERT INTO Professor VALUES (	'Gustafson M'	);
INSERT INTO Professor VALUES (	'Alvin Lebeck'	);
INSERT INTO Professor VALUES (	'Huettel L'	);
INSERT INTO Professor VALUES (	'Galen Reeves'	);
INSERT INTO Professor VALUES (	'Michael Gustafson '	);
INSERT INTO Professor VALUES (	'Richard Fair'	);
INSERT INTO Professor VALUES (	'Michael Zavlanos'	);
INSERT INTO Professor VALUES (	'Tyler Bletsch'	);
INSERT INTO Professor VALUES (	'Connel Fullenkamp'	);
INSERT INTO Professor VALUES (	'Fullenkamp'	);
INSERT INTO Professor VALUES (	'Fullenkamp C'	);
INSERT INTO Professor VALUES (	'Fullenkamp F'	);
INSERT INTO Professor VALUES (	'Fullenkamp, C.'	);
INSERT INTO Professor VALUES (	'Lori Leachman '	);
INSERT INTO Professor VALUES (	'Leachman, L'	);
INSERT INTO Professor VALUES (	'Fullenkamp '	);
INSERT INTO Professor VALUES (	'C. Fullenkamp'	);
INSERT INTO Professor VALUES (	'micheal F'	);
INSERT INTO Professor VALUES (	'Emily'	);
INSERT INTO Professor VALUES (	'CJ Skender'	);
INSERT INTO Professor VALUES (	'AJ'	);
INSERT INTO Professor VALUES (	'C. J. Skender'	);
INSERT INTO Professor VALUES (	'C. Skender'	);
INSERT INTO Professor VALUES (	'C.J. Skender'	);
INSERT INTO Professor VALUES (	'Charles Skender'	);
INSERT INTO Professor VALUES (	'Skender C'	);
INSERT INTO Professor VALUES (	'Skender CJ'	);
INSERT INTO Professor VALUES (	'Skender, C'	);
INSERT INTO Professor VALUES (	'C.K. Skinder '	);
INSERT INTO Professor VALUES (	'Michael Munger'	);
INSERT INTO Professor VALUES (	'Anna Jozefacka'	);
INSERT INTO Professor VALUES (	'Genna Miller'	);
INSERT INTO Professor VALUES (	'Miller, G'	);
INSERT INTO Professor VALUES (	'Thomas Nechyba'	);
INSERT INTO Professor VALUES (	'Abdulkadiroglu A'	);
INSERT INTO Professor VALUES (	'Nechyba T'	);
INSERT INTO Professor VALUES (	'Todd Saver'	);
INSERT INTO Professor VALUES (	'Atila A'	);
INSERT INTO Professor VALUES (	'Martin Zelder'	);
INSERT INTO Professor VALUES (	'Todd S'	);
INSERT INTO Professor VALUES (	'Todd Sarver'	);
INSERT INTO Professor VALUES (	'Zelder M'	);
INSERT INTO Professor VALUES (	'Zelder, M'	);
INSERT INTO Professor VALUES (	'Abdulkadiroglu  A'	);
INSERT INTO Professor VALUES (	'Atila Abdulkadiroglu'	);
INSERT INTO Professor VALUES (	'Chelsea E Garber'	);
INSERT INTO Professor VALUES (	'Michelle Connolly'	);
INSERT INTO Professor VALUES (	'Nechyba T, Zelder M'	);
INSERT INTO Professor VALUES (	'Nechyba'	);
INSERT INTO Professor VALUES (	'Abdulkadiroglu, A'	);
INSERT INTO Professor VALUES (	'Arcidiacono P'	);
INSERT INTO Professor VALUES (	'Kranton R.'	);
INSERT INTO Professor VALUES (	'Kranton R'	);
INSERT INTO Professor VALUES (	'Taylor Curtis R'	);
INSERT INTO Professor VALUES (	'Bahar Leventoglu'	);
INSERT INTO Professor VALUES (	'Curtis Taylor'	);
INSERT INTO Professor VALUES (	'Leventoglu'	);
INSERT INTO Professor VALUES (	'Rachel E. Kranton'	);
INSERT INTO Professor VALUES (	'Rachel Kranton'	);
INSERT INTO Professor VALUES (	'Levenglou B'	);
INSERT INTO Professor VALUES (	'Taylor C'	);
INSERT INTO Professor VALUES (	'Duncan Thomas'	);
INSERT INTO Professor VALUES (	'James Robert'	);
INSERT INTO Professor VALUES (	'James Roberts'	);
INSERT INTO Professor VALUES (	'Roberts'	);
INSERT INTO Professor VALUES (	'Roberts J'	);
INSERT INTO Professor VALUES (	'Thomas Duncan'	);
INSERT INTO Professor VALUES (	'Thomas Duncan '	);
INSERT INTO Professor VALUES (	'Robert J'	);
INSERT INTO Professor VALUES (	'Thomas, D'	);
INSERT INTO Professor VALUES (	'Maurel A'	);
INSERT INTO Professor VALUES (	'Connolly, M'	);
INSERT INTO Professor VALUES (	'andrea lanteri'	);
INSERT INTO Professor VALUES (	'Connolly M'	);
INSERT INTO Professor VALUES (	'Kehrig M'	);
INSERT INTO Professor VALUES (	'Keurhig M'	);
INSERT INTO Professor VALUES (	'Matthias K'	);
INSERT INTO Professor VALUES (	'Jaimovich N'	);
INSERT INTO Professor VALUES (	'M. Connolly'	);
INSERT INTO Professor VALUES (	'Emma Rasiel'	);
INSERT INTO Professor VALUES (	'Emma R & John C'	);
INSERT INTO Professor VALUES (	'Emma Rasiel & John Caccavale'	);
INSERT INTO Professor VALUES (	'Emma Rasiel, John Caccavale'	);
INSERT INTO Professor VALUES (	'Racial E, Caccavale J'	);
INSERT INTO Professor VALUES (	'Rasiel E'	);
INSERT INTO Professor VALUES (	'Emma Rasile '	);
INSERT INTO Professor VALUES (	'Professor CJ Skender'	);
INSERT INTO Professor VALUES (	'Skender, C.J. '	);
INSERT INTO Professor VALUES (	'John Folines III'	);
INSERT INTO Professor VALUES (	'Zanalda G'	);
INSERT INTO Professor VALUES (	'John Caccavale '	);
INSERT INTO Professor VALUES (	'John Caccavale'	);
INSERT INTO Professor VALUES (	'Charles Piot'	);
INSERT INTO Professor VALUES (	'Jason Brent'	);
INSERT INTO Professor VALUES (	'Jason Brent '	);
INSERT INTO Professor VALUES (	'Kevin Hoover'	);
INSERT INTO Professor VALUES (	'Rosenberg A'	);
INSERT INTO Professor VALUES (	'Gale Boyd '	);
INSERT INTO Professor VALUES (	'Neil De Marchi'	);
INSERT INTO Professor VALUES (	'Hans J Van Miegroet'	);
INSERT INTO Professor VALUES (	'Charlie Becker'	);
INSERT INTO Professor VALUES (	'Rosenberg A, Fjeld J (Fuqua)'	);
INSERT INTO Professor VALUES (	'Genna M'	);
INSERT INTO Professor VALUES (	'Miller G'	);
INSERT INTO Professor VALUES (	'Grace Kim'	);
INSERT INTO Professor VALUES (	'Grace Kim '	);
INSERT INTO Professor VALUES (	'Mary Beth'	);
INSERT INTO Professor VALUES (	'Mary Beth Fisher'	);
INSERT INTO Professor VALUES (	'Kim G'	);
INSERT INTO Professor VALUES (	'Rafael Dix-Carneiro '	);
INSERT INTO Professor VALUES (	'Lori Leachman'	);
INSERT INTO Professor VALUES (	'Munger; Rosenberg'	);
INSERT INTO Professor VALUES (	'Wang X'	);
INSERT INTO Professor VALUES (	'Caccavale, J'	);
INSERT INTO Professor VALUES (	'Caccavale J'	);
INSERT INTO Professor VALUES (	'Rasiel'	);
INSERT INTO Professor VALUES (	'Aino Levonmaa'	);
INSERT INTO Professor VALUES (	'E. Rasiel'	);
INSERT INTO Professor VALUES (	'Emma'	);
INSERT INTO Professor VALUES (	'Emma B Rasiel'	);
INSERT INTO Professor VALUES (	'Emma R'	);
INSERT INTO Professor VALUES (	'Emma Raisal'	);
INSERT INTO Professor VALUES (	'Levonmma, A'	);
INSERT INTO Professor VALUES (	'Raisel E'	);
INSERT INTO Professor VALUES (	'Emma Raisel'	);
INSERT INTO Professor VALUES (	'Connel Fullencamp,'	);
INSERT INTO Professor VALUES (	'George Tauchen'	);
INSERT INTO Professor VALUES (	'George Tauchen '	);
INSERT INTO Professor VALUES (	'Evan Jones'	);
INSERT INTO Professor VALUES (	'Thavolia Glymph and Seth Sanders'	);
INSERT INTO Professor VALUES (	'Thomason B'	);
INSERT INTO Professor VALUES (	'Andrew Patton'	);
INSERT INTO Professor VALUES (	'Cosmin, I'	);
INSERT INTO Professor VALUES (	'Graham D'	);
INSERT INTO Professor VALUES (	'D. Graham'	);
INSERT INTO Professor VALUES (	'Daniel Gramham'	);
INSERT INTO Professor VALUES (	'Yildirim H'	);
INSERT INTO Professor VALUES (	'Huseyin Yildirlm'	);
INSERT INTO Professor VALUES (	'Huseyin Yildirim'	);
INSERT INTO Professor VALUES (	'Joh Caccavale'	);
INSERT INTO Professor VALUES (	'Tim Bollerslev'	);
INSERT INTO Professor VALUES (	'Brian Weller'	);
INSERT INTO Professor VALUES (	'Bollerslev T'	);
INSERT INTO Professor VALUES (	'Boilerslev T'	);
INSERT INTO Professor VALUES (	'Kimbrough K'	);
INSERT INTO Professor VALUES (	'Hagy A'	);
INSERT INTO Professor VALUES (	'Bai Gao'	);
INSERT INTO Professor VALUES (	'Arlie Petters'	);
INSERT INTO Professor VALUES (	'Xaiver Mela'	);
INSERT INTO Professor VALUES (	'Miller, Aldrich'	);
INSERT INTO Professor VALUES (	'fullekamp '	);
INSERT INTO Professor VALUES (	'Skander CJ'	);
INSERT INTO Professor VALUES (	'Chelsea'	);
INSERT INTO Professor VALUES (	'Michelle C.'	);
INSERT INTO Professor VALUES (	'Miegroet H'	);
INSERT INTO Professor VALUES (	'John Caccavli '	);
INSERT INTO Professor VALUES (	':D forget '	);
INSERT INTO Professor VALUES (	'Emma Raisel '	);
INSERT INTO Professor VALUES (	'C. Fullencamp '	);
INSERT INTO Professor VALUES (	'William Darity'	);
INSERT INTO Professor VALUES (	'Jia Li'	);
INSERT INTO Professor VALUES (	'Anderson A'	);
INSERT INTO Professor VALUES (	'Anderson A.'	);
INSERT INTO Professor VALUES (	'Goodridge Shane'	);
INSERT INTO Professor VALUES (	'Jentleson'	);
INSERT INTO Professor VALUES (	'Amy Anderson'	);
INSERT INTO Professor VALUES (	'Kisha Daniels'	);
INSERT INTO Professor VALUES (	'David Malone'	);
INSERT INTO Professor VALUES (	'Susie Post Rust'	);
INSERT INTO Professor VALUES (	'Katehrine Hyde'	);
INSERT INTO Professor VALUES (	'Li Chen Chin'	);
INSERT INTO Professor VALUES (	'Tantum, S'	);
INSERT INTO Professor VALUES (	'Rebecca Simmons'	);
INSERT INTO Professor VALUES (	'Dr. G, Dr. Simmons'	);
INSERT INTO Professor VALUES (	'Greg Twiss, Rebecca Simmons'	);
INSERT INTO Professor VALUES (	'Nadeau J'	);
INSERT INTO Professor VALUES (	'Wilkins Aquino'	);
INSERT INTO Professor VALUES (	'Dr.G'	);
INSERT INTO Professor VALUES (	'Brian Mann'	);
INSERT INTO Professor VALUES (	'Lipp G'	);
INSERT INTO Professor VALUES (	'Michael Gastufson'	);
INSERT INTO Professor VALUES (	'Gavin, H'	);
INSERT INTO Professor VALUES (	'Kabala'	);
INSERT INTO Professor VALUES (	'Steven McCune'	);
INSERT INTO Professor VALUES (	'Pratson'	);
INSERT INTO Professor VALUES (	'Pratson L'	);
INSERT INTO Professor VALUES (	'Dolan'	);
INSERT INTO Professor VALUES (	'Cullen'	);
INSERT INTO Professor VALUES (	'Tim Johnson'	);
INSERT INTO Professor VALUES (	'Professor Michael D‘Alessandro'	);
INSERT INTO Professor VALUES (	'Gorecki K'	);
INSERT INTO Professor VALUES (	'Donahue J'	);
INSERT INTO Professor VALUES (	'Baran, Dominica'	);
INSERT INTO Professor VALUES (	'D. Marassa'	);
INSERT INTO Professor VALUES (	'Miller, S'	);
INSERT INTO Professor VALUES (	'Mcauliffe J'	);
INSERT INTO Professor VALUES (	'Vadde A'	);
INSERT INTO Professor VALUES (	'Neil Bell'	);
INSERT INTO Professor VALUES (	'Porter J'	);
INSERT INTO Professor VALUES (	'Rogers, H'	);
INSERT INTO Professor VALUES (	'Strandberg, V'	);
INSERT INTO Professor VALUES (	'Beckwith, S'	);
INSERT INTO Professor VALUES (	'Josh Striker'	);
INSERT INTO Professor VALUES (	'Clark C'	);
INSERT INTO Professor VALUES (	'Nora Bynum'	);
INSERT INTO Professor VALUES (	'Gary Dwyer'	);
INSERT INTO Professor VALUES (	'Will Wilson'	);
INSERT INTO Professor VALUES (	'Hinton D'	);
INSERT INTO Professor VALUES (	'Vidra'	);
INSERT INTO Professor VALUES (	'Joel Meyer'	);
INSERT INTO Professor VALUES (	'Joel M'	);
INSERT INTO Professor VALUES (	'Scott Winton'	);
INSERT INTO Professor VALUES (	'Charlotte Clark'	);
INSERT INTO Professor VALUES (	'Schauman M'	);
INSERT INTO Professor VALUES (	'lecturers from various departments'	);
INSERT INTO Professor VALUES (	'Jim Zhang'	);
INSERT INTO Professor VALUES (	'Lincoln Pratson'	);
INSERT INTO Professor VALUES (	'Emily Klein'	);
INSERT INTO Professor VALUES (	'Emily M. Klein'	);
INSERT INTO Professor VALUES (	'Glass'	);
INSERT INTO Professor VALUES (	'Klein E'	);
INSERT INTO Professor VALUES (	'Emily Kleins'	);
INSERT INTO Professor VALUES (	'Alexander Glass'	);
INSERT INTO Professor VALUES (	'Glass A'	);
INSERT INTO Professor VALUES (	'Klein'	);
INSERT INTO Professor VALUES (	'Klein, E'	);
INSERT INTO Professor VALUES (	'Emily Klein '	);
INSERT INTO Professor VALUES (	'A. Glass'	);
INSERT INTO Professor VALUES (	'Laifang Li'	);
INSERT INTO Professor VALUES (	'Lozier'	);
INSERT INTO Professor VALUES (	'Goldstein E'	);
INSERT INTO Professor VALUES (	'Nick Gessler'	);
INSERT INTO Professor VALUES (	'Drew Shindell'	);
INSERT INTO Professor VALUES (	'Shindell D'	);
INSERT INTO Professor VALUES (	'Alex Glass'	);
INSERT INTO Professor VALUES (	'Ong J'	);
INSERT INTO Professor VALUES (	'Glander K'	);
INSERT INTO Professor VALUES (	'Glander Ken'	);
INSERT INTO Professor VALUES (	'Jenny Tung'	);
INSERT INTO Professor VALUES (	'S. Churchill'	);
INSERT INTO Professor VALUES (	'Churchill S'	);
INSERT INTO Professor VALUES (	'Steven Churchill'	);
INSERT INTO Professor VALUES (	'Churchill, Steven'	);
INSERT INTO Professor VALUES (	'Steven Churchill '	);
INSERT INTO Professor VALUES (	'Emily Boehm '	);
INSERT INTO Professor VALUES (	'Tara Clarke'	);
INSERT INTO Professor VALUES (	'Newcity M'	);
INSERT INTO Professor VALUES (	'Mine Cetinkaya-Rundel-Layton'	);
INSERT INTO Professor VALUES (	'Geena Miller'	);
INSERT INTO Professor VALUES (	'Choffart G'	);
INSERT INTO Professor VALUES (	'Rachel'	);
INSERT INTO Professor VALUES (	'Screpanti F'	);
INSERT INTO Professor VALUES (	'Germain Choffart'	);
INSERT INTO Professor VALUES (	'Sandra Valnes Quammen'	);
INSERT INTO Professor VALUES (	'Valnes Quammen S'	);
INSERT INTO Professor VALUES (	'Stempniak K'	);
INSERT INTO Professor VALUES (	'Rothendler'	);
INSERT INTO Professor VALUES (	'Martha Van Der Drift'	);
INSERT INTO Professor VALUES (	'Valnes Quammen,Sandra L'	);
INSERT INTO Professor VALUES (	'Choffart'	);
INSERT INTO Professor VALUES (	'Dandrige E'	);
INSERT INTO Professor VALUES (	'Mdm. Provot'	);
INSERT INTO Professor VALUES (	'Tufenkian, Armand'	);
INSERT INTO Professor VALUES (	'Laura Iber '	);
INSERT INTO Professor VALUES (	'Filippo C.F. Screpanti'	);
INSERT INTO Professor VALUES (	'Blaise S'	);
INSERT INTO Professor VALUES (	'Brusson E'	);
INSERT INTO Professor VALUES (	'Christelle Gonthier'	);
INSERT INTO Professor VALUES (	'Victor Monnin'	);
INSERT INTO Professor VALUES (	'Magali Canoit'	);
INSERT INTO Professor VALUES (	'Clare Tufts & Sandra '	);
INSERT INTO Professor VALUES (	'Lauren Florand'	);
INSERT INTO Professor VALUES (	'Martha Van der Drift '	);
INSERT INTO Professor VALUES (	'Florand Lauren'	);
INSERT INTO Professor VALUES (	'van der Drift Martha'	);
INSERT INTO Professor VALUES (	'Deb Reisinger'	);
INSERT INTO Professor VALUES (	'Gonthier C'	);
INSERT INTO Professor VALUES (	'Saliot A'	);
INSERT INTO Professor VALUES (	'Clare Tufts'	);
INSERT INTO Professor VALUES (	'Jacob F'	);
INSERT INTO Professor VALUES (	'Longino, M'	);
INSERT INTO Professor VALUES (	'Monnin V'	);
INSERT INTO Professor VALUES (	'Solterer H'	);
INSERT INTO Professor VALUES (	'Michele Longino '	);
INSERT INTO Professor VALUES (	'Alexandra Beolke'	);
INSERT INTO Professor VALUES (	'Cori Crane'	);
INSERT INTO Professor VALUES (	'Henry A'	);
INSERT INTO Professor VALUES (	'Freytag S'	);
INSERT INTO Professor VALUES (	'Susanne Freytag'	);
INSERT INTO Professor VALUES (	'Corrina Egdorf'	);
INSERT INTO Professor VALUES (	'Brandt L'	);
INSERT INTO Professor VALUES (	'Kaupp S'	);
INSERT INTO Professor VALUES (	'Helen Szate'	);
INSERT INTO Professor VALUES (	'Susanne Freitag'	);
INSERT INTO Professor VALUES (	'Freytag'	);
INSERT INTO Professor VALUES (	'Freytag, S'	);
INSERT INTO Professor VALUES (	'Henry A.'	);
INSERT INTO Professor VALUES (	'Norberg, Jakob'	);
INSERT INTO Professor VALUES (	'Schmidtz C'	);
INSERT INTO Professor VALUES (	'Donahue, W'	);
INSERT INTO Professor VALUES (	'Dolan,Kristen'	);
INSERT INTO Professor VALUES (	'Pickford H'	);
INSERT INTO Professor VALUES (	'April H'	);
INSERT INTO Professor VALUES (	'Boyd D'	);
INSERT INTO Professor VALUES (	'David Boyd'	);
INSERT INTO Professor VALUES (	'Nicole Barnes'	);
INSERT INTO Professor VALUES (	'Gabriel Rosenberg'	);
INSERT INTO Professor VALUES (	'Kearsley Stewart'	);
INSERT INTO Professor VALUES (	'Eve Puffer'	);
INSERT INTO Professor VALUES (	'Christina K'	);
INSERT INTO Professor VALUES (	'Frank Sloan'	);
INSERT INTO Professor VALUES (	'Grosz,Elizabeth'	);
INSERT INTO Professor VALUES (	'Saskia Cornes '	);
INSERT INTO Professor VALUES (	'Brenna Casey'	);
INSERT INTO Professor VALUES (	'Hajnalka Kovacs'	);
INSERT INTO Professor VALUES (	'Barnes N'	);
INSERT INTO Professor VALUES (	'Malegam J'	);
INSERT INTO Professor VALUES (	'Joshua Sosin'	);
INSERT INTO Professor VALUES (	'Devine'	);
INSERT INTO Professor VALUES (	'Thorne'	);
INSERT INTO Professor VALUES (	'Gasbar G'	);
INSERT INTO Professor VALUES (	'Wilson G'	);
INSERT INTO Professor VALUES (	'G. Wilson'	);
INSERT INTO Professor VALUES (	'Humphreys'	);
INSERT INTO Professor VALUES (	'Ramaswamy S'	);
INSERT INTO Professor VALUES (	'Fasan J'	);
INSERT INTO Professor VALUES (	'Josh Sosin'	);
INSERT INTO Professor VALUES (	'Paige Welch'	);
INSERT INTO Professor VALUES (	'Adam Mestyan'	);
INSERT INTO Professor VALUES (	'Vasant Kaiwar'	);
INSERT INTO Professor VALUES (	'Miller M'	);
INSERT INTO Professor VALUES (	'Elrod A'	);
INSERT INTO Professor VALUES (	'Professor Wilson'	);
INSERT INTO Professor VALUES (	'Gerald Wilson '	);
INSERT INTO Professor VALUES (	'Wilson,Gerald L'	);
INSERT INTO Professor VALUES (	'Prasenjit Duara'	);
INSERT INTO Professor VALUES (	'Nicole Barnes '	);
INSERT INTO Professor VALUES (	'Kristen Dolan '	);
INSERT INTO Professor VALUES (	'Martin Miller'	);
INSERT INTO Professor VALUES (	'Chappel J'	);
INSERT INTO Professor VALUES (	'Huston R'	);
INSERT INTO Professor VALUES (	'Nancy MacLean'	);
INSERT INTO Professor VALUES (	'Karin Shapiro'	);
INSERT INTO Professor VALUES (	'Nancy MacLean '	);
INSERT INTO Professor VALUES (	'Emily F and Yueran Z'	);
INSERT INTO Professor VALUES (	'Litzinger, R.'	);
INSERT INTO Professor VALUES (	'Laura Lieber'	);
INSERT INTO Professor VALUES (	'Bach,Rebecca L.'	);
INSERT INTO Professor VALUES (	'Ferejohn'	);
INSERT INTO Professor VALUES (	'Aaron Dinin'	);
INSERT INTO Professor VALUES (	'Salsman Azhar & Robert Hallford'	);
INSERT INTO Professor VALUES (	'Multiple Instructors'	);
INSERT INTO Professor VALUES (	'Kathie Amato'	);
INSERT INTO Professor VALUES (	'Meyerhoff E'	);
INSERT INTO Professor VALUES (	'Jessica Namakkal'	);
INSERT INTO Professor VALUES (	'Abdul Satter Jawad'	);
INSERT INTO Professor VALUES (	'Eli Meyerhoff'	);
INSERT INTO Professor VALUES (	'Namakkal J'	);
INSERT INTO Professor VALUES (	'Wiencek, F.'	);
INSERT INTO Professor VALUES (	'David Zielinski'	);
INSERT INTO Professor VALUES (	'Casa L'	);
INSERT INTO Professor VALUES (	'Azu Saito'	);
INSERT INTO Professor VALUES (	'Kurokawa N'	);
INSERT INTO Professor VALUES (	'Naoko Kurokawa'	);
INSERT INTO Professor VALUES (	'Endo; Kurokawa'	);
INSERT INTO Professor VALUES (	'Endo'	);
INSERT INTO Professor VALUES (	'Endo Hitomi'	);
INSERT INTO Professor VALUES (	'Azusa Saito'	);
INSERT INTO Professor VALUES (	'Endo H'	);
INSERT INTO Professor VALUES (	'Kurokawa'	);
INSERT INTO Professor VALUES (	'Eunyoung Kim'	);
INSERT INTO Professor VALUES (	'Eunyeong Kim'	);
INSERT INTO Professor VALUES (	'Kim E'	);
INSERT INTO Professor VALUES (	'Kim, H'	);
INSERT INTO Professor VALUES (	'Hae-Young Kim'	);
INSERT INTO Professor VALUES (	'Kim, Hae-Young'	);
INSERT INTO Professor VALUES (	'Michaela Janan'	);
INSERT INTO Professor VALUES (	'Gareth Price '	);
INSERT INTO Professor VALUES (	'Brezil D'	);
INSERT INTO Professor VALUES (	'Liu, D'	);
INSERT INTO Professor VALUES (	'Paredes L'	);
INSERT INTO Professor VALUES (	'Gareth Price'	);
INSERT INTO Professor VALUES (	'Gail Clements'	);
INSERT INTO Professor VALUES (	'Baran D'	);
INSERT INTO Professor VALUES (	'Diaz M'	);
INSERT INTO Professor VALUES (	'Price G'	);
INSERT INTO Professor VALUES (	'Andrews E'	);
INSERT INTO Professor VALUES (	'Andrew E'	);
INSERT INTO Professor VALUES (	'Andrews Edna'	);
INSERT INTO Professor VALUES (	'Landesberg E'	);
INSERT INTO Professor VALUES (	'Michael G'	);
INSERT INTO Professor VALUES (	'Cole Rizki'	);
INSERT INTO Professor VALUES (	'Bose-Kolanu A (Bobo)'	);
INSERT INTO Professor VALUES (	'Wiegman'	);
INSERT INTO Professor VALUES (	'Robyn Wiegman'	);
INSERT INTO Professor VALUES (	'Saskia Ziolkowski '	);
INSERT INTO Professor VALUES (	'Flanagan O'	);
INSERT INTO Professor VALUES (	'Rey Chow, Markos Hadjioannou'	);
INSERT INTO Professor VALUES (	'Chow R, Hadjioannou M'	);
INSERT INTO Professor VALUES (	'Dorfman A'	);
INSERT INTO Professor VALUES (	'Bartlett K'	);
INSERT INTO Professor VALUES (	'Bartlett K '	);
INSERT INTO Professor VALUES (	'Jameson F'	);
INSERT INTO Professor VALUES (	'Karim Agawal'	);
INSERT INTO Professor VALUES (	'Robyn Wigman'	);
INSERT INTO Professor VALUES (	'Ziolkowski S'	);
INSERT INTO Professor VALUES (	'Kraines D'	);
INSERT INTO Professor VALUES (	'Yu Pan'	);
INSERT INTO Professor VALUES (	'Ashleigh Thomas'	);
INSERT INTO Professor VALUES (	'Blake Lewis Spring 2015'	);
INSERT INTO Professor VALUES (	'Yu Fan'	);
INSERT INTO Professor VALUES (	'Blake L'	);
INSERT INTO Professor VALUES (	'Diaz H'	);
INSERT INTO Professor VALUES (	'Leverson C'	);
INSERT INTO Professor VALUES (	'Michael Bell'	);
INSERT INTO Professor VALUES (	'Goetz, A'	);
INSERT INTO Professor VALUES (	'Shanshan (Ph.D student)'	);
INSERT INTO Professor VALUES (	'Noah Lavine'	);
INSERT INTO Professor VALUES (	'Sarah Schott'	);
INSERT INTO Professor VALUES (	'Brendan Williamson'	);
INSERT INTO Professor VALUES (	'Bookman, J'	);
INSERT INTO Professor VALUES (	'Schott S'	);
INSERT INTO Professor VALUES (	'Shalla Hanson'	);
INSERT INTO Professor VALUES (	'Fry'	);
INSERT INTO Professor VALUES (	'Ingird Dauechies'	);
INSERT INTO Professor VALUES (	'Wei N'	);
INSERT INTO Professor VALUES (	'Hahn H'	);
INSERT INTO Professor VALUES (	'Heekyoung Hahn'	);
INSERT INTO Professor VALUES (	'Brian Fitzpatrick'	);
INSERT INTO Professor VALUES (	'Hanh. H.'	);
INSERT INTO Professor VALUES (	'Brian D Fitzpatrick'	);
INSERT INTO Professor VALUES (	'Heekyoung H'	);
INSERT INTO Professor VALUES (	'H. Hahn'	);
INSERT INTO Professor VALUES (	'Ding Ma'	);
INSERT INTO Professor VALUES (	'B Fizpatrick '	);
INSERT INTO Professor VALUES (	'Bell M'	);
INSERT INTO Professor VALUES (	'Watson '	);
INSERT INTO Professor VALUES (	'Arya Roy'	);
INSERT INTO Professor VALUES (	'Bray C'	);
INSERT INTO Professor VALUES (	'BRIAN F.'	);
INSERT INTO Professor VALUES (	'Brian Fitzpatric'	);
INSERT INTO Professor VALUES (	'Cahill J'	);
INSERT INTO Professor VALUES (	'Clark Bray'	);
INSERT INTO Professor VALUES (	'Cooke'	);
INSERT INTO Professor VALUES (	'Cornwell C'	);
INSERT INTO Professor VALUES (	'Cornwell, C'	);
INSERT INTO Professor VALUES (	'Dr. Lipnowski'	);
INSERT INTO Professor VALUES (	'E. Barbano'	);
INSERT INTO Professor VALUES (	'Greg Herschlag'	);
INSERT INTO Professor VALUES (	'Jameson Cahill'	);
INSERT INTO Professor VALUES (	'Lipnowski M'	);
INSERT INTO Professor VALUES (	'Lizzy Huang'	);
INSERT INTO Professor VALUES (	'Nathan Totz'	);
INSERT INTO Professor VALUES (	'Roy A'	);
INSERT INTO Professor VALUES (	'Wang Y'	);
INSERT INTO Professor VALUES (	'Yi Wang (Grace)'	);
INSERT INTO Professor VALUES (	'Zhenan Zhou'	);
INSERT INTO Professor VALUES (	'Zhennan Zhou'	);
INSERT INTO Professor VALUES (	'Zhou Z'	);
INSERT INTO Professor VALUES (	'Li Lei'	);
INSERT INTO Professor VALUES (	'C. Bray'	);
INSERT INTO Professor VALUES (	'Brian Fitz'	);
INSERT INTO Professor VALUES (	'Brian Firzpatrick'	);
INSERT INTO Professor VALUES (	'Abel M'	);
INSERT INTO Professor VALUES (	'Able M'	);
INSERT INTO Professor VALUES (	'Adam Levine'	);
INSERT INTO Professor VALUES (	'E. Miller'	);
INSERT INTO Professor VALUES (	'Ezra Miller'	);
INSERT INTO Professor VALUES (	'John Harer'	);
INSERT INTO Professor VALUES (	'Leslie Saper'	);
INSERT INTO Professor VALUES (	'Lilian Pierce'	);
INSERT INTO Professor VALUES (	'Michael Abel'	);
INSERT INTO Professor VALUES (	'Pierce'	);
INSERT INTO Professor VALUES (	'Richard Hain'	);
INSERT INTO Professor VALUES (	'Robles C'	);
INSERT INTO Professor VALUES (	'Saper L'	);
INSERT INTO Professor VALUES (	'Turnage-Butterbaugh C'	);
INSERT INTO Professor VALUES (	'Caroline Turnage-Butterbaugh'	);
INSERT INTO Professor VALUES (	'Akos Nagy'	);
INSERT INTO Professor VALUES (	'Turange-Butterbaugh Caroline'	);
INSERT INTO Professor VALUES (	'Brian Fitzpatrick '	);
INSERT INTO Professor VALUES (	'Saper Leslie'	);
INSERT INTO Professor VALUES (	'A. Basak'	);
INSERT INTO Professor VALUES (	'Cheng Li'	);
INSERT INTO Professor VALUES (	'Gugan Chandrashekharmalli Thoppe'	);
INSERT INTO Professor VALUES (	'Heller K'	);
INSERT INTO Professor VALUES (	'Herzog D'	);
INSERT INTO Professor VALUES (	'Johnathan Mattingly'	);
INSERT INTO Professor VALUES (	'Jonathan Mattingly'	);
INSERT INTO Professor VALUES (	'Mattingly, J.'	);
INSERT INTO Professor VALUES (	'Mela X'	);
INSERT INTO Professor VALUES (	'Rundel C'	);
INSERT INTO Professor VALUES (	'Si Tang'	);
INSERT INTO Professor VALUES (	'Katherine Heller '	);
INSERT INTO Professor VALUES (	'Anirban Basak'	);
INSERT INTO Professor VALUES (	'David Kraines'	);
INSERT INTO Professor VALUES (	'Pierce L'	);
INSERT INTO Professor VALUES (	'Professor Caroline TB'	);
INSERT INTO Professor VALUES (	'Jayce Getz'	);
INSERT INTO Professor VALUES (	'Joseph Mattingly'	);
INSERT INTO Professor VALUES (	'Hubert Bray'	);
INSERT INTO Professor VALUES (	'Mathew Junge'	);
INSERT INTO Professor VALUES (	'Rich Durrett'	);
INSERT INTO Professor VALUES (	'Richard Durrett'	);
INSERT INTO Professor VALUES (	'Matthew Junge'	);
INSERT INTO Professor VALUES (	'Matt Junge'	);
INSERT INTO Professor VALUES (	'Matthew Junge '	);
INSERT INTO Professor VALUES (	'Wolpert'	);
INSERT INTO Professor VALUES (	'Xiaver Mela'	);
INSERT INTO Professor VALUES (	'Hershlag G'	);
INSERT INTO Professor VALUES (	'Yulong Lu'	);
INSERT INTO Professor VALUES (	'Bilinsky L'	);
INSERT INTO Professor VALUES (	'Nolan J'	);
INSERT INTO Professor VALUES (	'Lydia Bilinsky'	);
INSERT INTO Professor VALUES (	'/'	);
INSERT INTO Professor VALUES (	'Jianfeng LU'	);
INSERT INTO Professor VALUES (	'Fernandes De Oliveira G'	);
INSERT INTO Professor VALUES (	'Jeffrey Wong'	);
INSERT INTO Professor VALUES (	'Paul Bendich'	);
INSERT INTO Professor VALUES (	'David Lawlor'	);
INSERT INTO Professor VALUES (	'Greg Malen'	);
INSERT INTO Professor VALUES (	'Additon'	);
INSERT INTO Professor VALUES (	'Nicolas Addington'	);
INSERT INTO Professor VALUES (	'William Pardon'	);
INSERT INTO Professor VALUES (	'Chad Schoen '	);
INSERT INTO Professor VALUES (	'Henry Adams'	);
INSERT INTO Professor VALUES (	'MAURO MAGGIONI'	);
INSERT INTO Professor VALUES (	'Michael Reed'	);
INSERT INTO Professor VALUES (	'Ng L'	);
INSERT INTO Professor VALUES (	'Reed M'	);
INSERT INTO Professor VALUES (	'Michael Reed '	);
INSERT INTO Professor VALUES (	'Saulo Orizaga'	);
INSERT INTO Professor VALUES (	'Random'	);
INSERT INTO Professor VALUES (	'Tau Shean Lim'	);
INSERT INTO Professor VALUES (	'Tom Beale, James Nolen'	);
INSERT INTO Professor VALUES (	'Paul Bendlich'	);
INSERT INTO Professor VALUES (	'Dimtry Vagner (actually a PhD student at Duke)'	);
INSERT INTO Professor VALUES (	'Dmitry Vagner'	);
INSERT INTO Professor VALUES (	'Chad Schoen'	);
INSERT INTO Professor VALUES (	'Robert Calderbank'	);
INSERT INTO Professor VALUES (	'Mark Stern'	);
INSERT INTO Professor VALUES (	'Liu J'	);
INSERT INTO Professor VALUES (	'Mela Xavier'	);
INSERT INTO Professor VALUES (	'Petters'	);
INSERT INTO Professor VALUES (	'Petters A'	);
INSERT INTO Professor VALUES (	'Xavier Mela'	);
INSERT INTO Professor VALUES (	'Prof Chad Schoen'	);
INSERT INTO Professor VALUES (	'Goncalo M. Fernandes de Oliveira'	);
INSERT INTO Professor VALUES (	'Prof Lenny Ng'	);
INSERT INTO Professor VALUES (	'Prof Mike Reed'	);
INSERT INTO Professor VALUES (	'Prof Colleen Robles'	);
INSERT INTO Professor VALUES (	'Shan shan'	);
INSERT INTO Professor VALUES (	'Gunderson Ryan'	);
INSERT INTO Professor VALUES (	'Brain Fitzpatrick '	);
INSERT INTO Professor VALUES (	'Mike Moon'	);
INSERT INTO Professor VALUES (	' Michael Abel'	);
INSERT INTO Professor VALUES (	'Daubechies I'	);
INSERT INTO Professor VALUES (	'Ingrid Daubiechies'	);
INSERT INTO Professor VALUES (	'Hugh Bray'	);
INSERT INTO Professor VALUES (	'Benjamin Cooke'	);
INSERT INTO Professor VALUES (	'Harer J'	);
INSERT INTO Professor VALUES (	'Aspinwall P'	);
INSERT INTO Professor VALUES (	'Paul B'	);
INSERT INTO Professor VALUES (	'Reichert M'	);
INSERT INTO Professor VALUES (	'Volker Blum'	);
INSERT INTO Professor VALUES (	'Stefano Curtarolo'	);
INSERT INTO Professor VALUES (	'Stafano Curtolio'	);
INSERT INTO Professor VALUES (	'Zhong P'	);
INSERT INTO Professor VALUES (	'Michael R. Gustafson'	);
INSERT INTO Professor VALUES (	'Mary C'	);
INSERT INTO Professor VALUES (	'Reeves M'	);
INSERT INTO Professor VALUES (	'George Grody'	);
INSERT INTO Professor VALUES (	'Grody G'	);
INSERT INTO Professor VALUES (	'Tiryakian E'	);
INSERT INTO Professor VALUES (	'Jones E'	);
INSERT INTO Professor VALUES (	'Ed T.'	);
INSERT INTO Professor VALUES (	'Ed Tiryakian'	);
INSERT INTO Professor VALUES (	'Edwyn Tiryakian'	);
INSERT INTO Professor VALUES (	'Tiryakian'	);
INSERT INTO Professor VALUES (	'Reeves, M'	);
INSERT INTO Professor VALUES (	'Nordgren C'	);
INSERT INTO Professor VALUES (	'Moore J'	);
INSERT INTO Professor VALUES (	'Pi-Kuei Tu'	);
INSERT INTO Professor VALUES (	'Nick Stoia'	);
INSERT INTO Professor VALUES (	'Linnartz E'	);
INSERT INTO Professor VALUES (	'Linnartz, Elizabeth'	);
INSERT INTO Professor VALUES (	'Reed'	);
INSERT INTO Professor VALUES (	'Simmons'	);
INSERT INTO Professor VALUES (	'Simmons B'	);
INSERT INTO Professor VALUES (	'Hawkins M'	);
INSERT INTO Professor VALUES (	'Heid, D'	);
INSERT INTO Professor VALUES (	'Heid D'	);
INSERT INTO Professor VALUES (	'Kevin Van Sant'	);
INSERT INTO Professor VALUES (	'Dewey Lawson'	);
INSERT INTO Professor VALUES (	'Dewey Lawson '	);
INSERT INTO Professor VALUES (	'Louise Meintjes'	);
INSERT INTO Professor VALUES (	'Meintjes L'	);
INSERT INTO Professor VALUES (	'T. Brothers'	);
INSERT INTO Professor VALUES (	'Sccuria A'	);
INSERT INTO Professor VALUES (	'Bonus A'	);
INSERT INTO Professor VALUES (	'Meredith Graham'	);
INSERT INTO Professor VALUES (	'Zimmerman, R'	);
INSERT INTO Professor VALUES (	'Jane Hawkins'	);
INSERT INTO Professor VALUES (	'Randall Love'	);
INSERT INTO Professor VALUES (	'Love'	);
INSERT INTO Professor VALUES (	'Federle T'	);
INSERT INTO Professor VALUES (	'David Heid'	);
INSERT INTO Professor VALUES (	'Gilliam'	);
INSERT INTO Professor VALUES (	'Larry Todd'	);
INSERT INTO Professor VALUES (	'Todd Larry'	);
INSERT INTO Professor VALUES (	'Todd L'	);
INSERT INTO Professor VALUES (	'Bryan Gilliam'	);
INSERT INTO Professor VALUES (	'Robert Parkins'	);
INSERT INTO Professor VALUES (	'Nicholas Stoia'	);
INSERT INTO Professor VALUES (	'Kelley, A'	);
INSERT INTO Professor VALUES (	'Moesenbichler-Bryant Verena'	);
INSERT INTO Professor VALUES (	'Phillip Rupprecht'	);
INSERT INTO Professor VALUES (	'Kelley A'	);
INSERT INTO Professor VALUES (	'Davidson H'	);
INSERT INTO Professor VALUES (	'H. Davidson'	);
INSERT INTO Professor VALUES (	'Davidson, H'	);
INSERT INTO Professor VALUES (	'Roberts F'	);
INSERT INTO Professor VALUES (	'Finucane D'	);
INSERT INTO Professor VALUES (	'Christina Williams'	);
INSERT INTO Professor VALUES (	'Murphy K'	);
INSERT INTO Professor VALUES (	'Minna Ng'	);
INSERT INTO Professor VALUES (	'Leo White'	);
INSERT INTO Professor VALUES (	'Scott Huettel'	);
INSERT INTO Professor VALUES (	'Bhandawat V'	);
INSERT INTO Professor VALUES (	'Thomas Newpher'	);
INSERT INTO Professor VALUES (	'Williams C'	);
INSERT INTO Professor VALUES (	'Williams'	);
INSERT INTO Professor VALUES (	'Bilbo, Staci'	);
INSERT INTO Professor VALUES (	'Bell D, Wardle M, Jenson D'	);
INSERT INTO Professor VALUES (	'Platt M, White L, Roberts C, Harris L, Johnson E'	);
INSERT INTO Professor VALUES (	'Bhandawat, Vikas'	);
INSERT INTO Professor VALUES (	'D Rubin'	);
INSERT INTO Professor VALUES (	'De Brigard F'	);
INSERT INTO Professor VALUES (	'Ng M'	);
INSERT INTO Professor VALUES (	'Hunter bandy'	);
INSERT INTO Professor VALUES (	'Volkan P'	);
INSERT INTO Professor VALUES (	'Amir'	);
INSERT INTO Professor VALUES (	'Branson S'	);
INSERT INTO Professor VALUES (	'Campbell M'	);
INSERT INTO Professor VALUES (	'Robert Brandon '	);
INSERT INTO Professor VALUES (	'Janiack R'	);
INSERT INTO Professor VALUES (	'Andrew Janiak'	);
INSERT INTO Professor VALUES (	'Rosenberg, A'	);
INSERT INTO Professor VALUES (	'Alexander Rosenberg'	);
INSERT INTO Professor VALUES (	'Heather Wallace'	);
INSERT INTO Professor VALUES (	'Jin Hu'	);
INSERT INTO Professor VALUES (	'Nathaniel Gindele'	);
INSERT INTO Professor VALUES (	'Aaron Ancell'	);
INSERT INTO Professor VALUES (	'Aryn Conrad'	);
INSERT INTO Professor VALUES (	'Bunch L'	);
INSERT INTO Professor VALUES (	'Conrad A'	);
INSERT INTO Professor VALUES (	'D. Stevens'	);
INSERT INTO Professor VALUES (	'Heather Marie Wallace'	);
INSERT INTO Professor VALUES (	'Lok Chan'	);
INSERT INTO Professor VALUES (	'Lok Chi Chan'	);
INSERT INTO Professor VALUES (	'Michael Campbell'	);
INSERT INTO Professor VALUES (	'Sides J'	);
INSERT INTO Professor VALUES (	'Stephens D'	);
INSERT INTO Professor VALUES (	'Um S'	);
INSERT INTO Professor VALUES (	'Flanagan, O'	);
INSERT INTO Professor VALUES (	'Ferejohns M'	);
INSERT INTO Professor VALUES (	'A. Janiak'	);
INSERT INTO Professor VALUES (	'Janiak'	);
INSERT INTO Professor VALUES (	'A janeic'	);
INSERT INTO Professor VALUES (	'Micheal Ferejohns'	);
INSERT INTO Professor VALUES (	'M ferejohn'	);
INSERT INTO Professor VALUES (	'Ferejohn, M'	);
INSERT INTO Professor VALUES (	'Bernstein, S'	);
INSERT INTO Professor VALUES (	'Brigard'	);
INSERT INTO Professor VALUES (	'Karen Neander'	);
INSERT INTO Professor VALUES (	'Wong'	);
INSERT INTO Professor VALUES (	'Wong, D.'	);
INSERT INTO Professor VALUES (	'Brandon R'	);
INSERT INTO Professor VALUES (	'Munger'	);
INSERT INTO Professor VALUES (	'Buchanan'	);
INSERT INTO Professor VALUES (	'David Wong'	);
INSERT INTO Professor VALUES (	'Wong, D'	);
INSERT INTO Professor VALUES (	'Wayne Norman'	);
INSERT INTO Professor VALUES (	'Wang D'	);
INSERT INTO Professor VALUES (	'Brandon R/ McShea D'	);
INSERT INTO Professor VALUES (	'Professor Robert Brandon'	);
INSERT INTO Professor VALUES (	'Robert Brandon'	);
INSERT INTO Professor VALUES (	'Robert Brandon; Dan McShea'	);
INSERT INTO Professor VALUES (	'Owen Flanagan'	);
INSERT INTO Professor VALUES (	'Peter van Inwagen'	);
INSERT INTO Professor VALUES (	'Neander'	);
INSERT INTO Professor VALUES (	'Professor Andrew Janiak'	);
INSERT INTO Professor VALUES (	'Hawkins J'	);
INSERT INTO Professor VALUES (	'Alex D'	);
INSERT INTO Professor VALUES (	'Wong D'	);
INSERT INTO Professor VALUES (	'Joseph Nelson'	);
INSERT INTO Professor VALUES (	'Ashutosh V Kotwal'	);
INSERT INTO Professor VALUES (	'Robert Brown'	);
INSERT INTO Professor VALUES (	'Roxanne Springer'	);
INSERT INTO Professor VALUES (	'Mark Kruse'	);
INSERT INTO Professor VALUES (	'Chris Walter'	);
INSERT INTO Professor VALUES (	'Finnagan'	);
INSERT INTO Professor VALUES (	'Welsh J'	);
INSERT INTO Professor VALUES (	'Lisa'	);
INSERT INTO Professor VALUES (	'Jindra,Lisa K'	);
INSERT INTO Professor VALUES (	'Maria Finnegan'	);
INSERT INTO Professor VALUES (	'Sheri XXXX'	);
INSERT INTO Professor VALUES (	'Miller T'	);
INSERT INTO Professor VALUES (	'Brian Rosenthal'	);
INSERT INTO Professor VALUES (	'Hampton, J'	);
INSERT INTO Professor VALUES (	'Bowen J'	);
INSERT INTO Professor VALUES (	'Kaufmann S'	);
INSERT INTO Professor VALUES (	'KS Lee'	);
INSERT INTO Professor VALUES (	'Kwak T'	);
INSERT INTO Professor VALUES (	'Lee J'	);
INSERT INTO Professor VALUES (	'Steven Kaufmann'	);
INSERT INTO Professor VALUES (	'Brame'	);
INSERT INTO Professor VALUES (	'Robert Brame'	);
INSERT INTO Professor VALUES (	'John O.'	);
INSERT INTO Professor VALUES (	'Franca Alphin'	);
INSERT INTO Professor VALUES (	'McNally'	);
INSERT INTO Professor VALUES (	'Kim McNally'	);
INSERT INTO Professor VALUES (	'Janis Hampton'	);
INSERT INTO Professor VALUES (	'Teitsworth, Stephen'	);
INSERT INTO Professor VALUES (	'Glenn Edwards '	);
INSERT INTO Professor VALUES (	'Glenn E'	);
INSERT INTO Professor VALUES (	'Ying Wu'	);
INSERT INTO Professor VALUES (	'Gauthier, Daniel'	);
INSERT INTO Professor VALUES (	'A. Goshaw'	);
INSERT INTO Professor VALUES (	'Alfred Goshaw'	);
INSERT INTO Professor VALUES (	'Phillips B'	);
INSERT INTO Professor VALUES (	'Albert Chang'	);
INSERT INTO Professor VALUES (	'Henry Greenside'	);
INSERT INTO Professor VALUES (	'Calvin Howell'	);
INSERT INTO Professor VALUES (	'Robert G. Brown'	);
INSERT INTO Professor VALUES (	'Gleb Finkelstein'	);
INSERT INTO Professor VALUES (	'Finkelstein G'	);
INSERT INTO Professor VALUES (	'Seog Oh'	);
INSERT INTO Professor VALUES (	'Robert P. Behringer'	);
INSERT INTO Professor VALUES (	'Ayana Arce'	);
INSERT INTO Professor VALUES (	'Robert P Behringer'	);
INSERT INTO Professor VALUES (	'Steffan Bass'	);
INSERT INTO Professor VALUES (	'Lawson D'	);
INSERT INTO Professor VALUES (	'roy'	);
INSERT INTO Professor VALUES (	'Behringer R'	);
INSERT INTO Professor VALUES (	'Napoli'	);
INSERT INTO Professor VALUES (	'Rosenberg'	);
INSERT INTO Professor VALUES (	'Georg Vanberg'	);
INSERT INTO Professor VALUES (	'Munger and Salsman'	);
INSERT INTO Professor VALUES (	'Peter Feaver'	);
INSERT INTO Professor VALUES (	'Feaver P'	);
INSERT INTO Professor VALUES (	'Atkins J'	);
INSERT INTO Professor VALUES (	'Gillespie M'	);
INSERT INTO Professor VALUES (	'DEMARCHI S'	);
INSERT INTO Professor VALUES (	'Knight J'	);
INSERT INTO Professor VALUES (	'Micheal Munger'	);
INSERT INTO Professor VALUES (	'Hanagan N'	);
INSERT INTO Professor VALUES (	'Balcells L'	);
INSERT INTO Professor VALUES (	'Munger M'	);
INSERT INTO Professor VALUES (	'Ruth Grant'	);
INSERT INTO Professor VALUES (	'Keren'	);
INSERT INTO Professor VALUES (	'Jonathan Anomaly'	);
INSERT INTO Professor VALUES (	'Anomaly J'	);
INSERT INTO Professor VALUES (	'Hardt M'	);
INSERT INTO Professor VALUES (	'Michael Hardt'	);
INSERT INTO Professor VALUES (	'Emerson Niou'	);
INSERT INTO Professor VALUES (	'Kirshner A'	);
INSERT INTO Professor VALUES (	'Scott De Marchi'	);
INSERT INTO Professor VALUES (	'Manion M'	);
INSERT INTO Professor VALUES (	'Manion,Melanie'	);
INSERT INTO Professor VALUES (	'Richard Salsman'	);
INSERT INTO Professor VALUES (	'Beattie D'	);
INSERT INTO Professor VALUES (	'Kristin Goss'	);
INSERT INTO Professor VALUES (	'Brian Hook'	);
INSERT INTO Professor VALUES (	'Natalie Goldring'	);
INSERT INTO Professor VALUES (	'Magda'	);
INSERT INTO Professor VALUES (	'MacMullen, Ian'	);
INSERT INTO Professor VALUES (	'Vieth A'	);
INSERT INTO Professor VALUES (	'Grimes C'	);
INSERT INTO Professor VALUES (	'Jorgianne Robinson'	);
INSERT INTO Professor VALUES (	'Jorgianne, R'	);
INSERT INTO Professor VALUES (	'Karen L Murphy'	);
INSERT INTO Professor VALUES (	'Wilbourn and Hard'	);
INSERT INTO Professor VALUES (	'Sarah Gaither'	);
INSERT INTO Professor VALUES (	'cabeza'	);
INSERT INTO Professor VALUES (	'Mitroff S'	);
INSERT INTO Professor VALUES (	'Makeba Wilbourn'	);
INSERT INTO Professor VALUES (	'James Shah'	);
INSERT INTO Professor VALUES (	'Robinson J'	);
INSERT INTO Professor VALUES (	'Shah, J'	);
INSERT INTO Professor VALUES (	'Dr. Rosenthal'	);
INSERT INTO Professor VALUES (	'Nancy Zucker'	);
INSERT INTO Professor VALUES (	'rosenthal'	);
INSERT INTO Professor VALUES (	'Rosenthal M'	);
INSERT INTO Professor VALUES (	'Rosenthal, M'	);
INSERT INTO Professor VALUES (	'Rosenthal,. M'	);
INSERT INTO Professor VALUES (	'Zucker N'	);
INSERT INTO Professor VALUES (	'Mark Rosenthal'	);
INSERT INTO Professor VALUES (	'Mark Z. Rosenthal'	);
INSERT INTO Professor VALUES (	'Karen Murphy'	);
INSERT INTO Professor VALUES (	'Amir H Rezvani'	);
INSERT INTO Professor VALUES (	'Shelby'	);
INSERT INTO Professor VALUES (	'Shelby R'	);
INSERT INTO Professor VALUES (	'George M'	);
INSERT INTO Professor VALUES (	'Kotter-Gruehn D'	);
INSERT INTO Professor VALUES (	'Sikkema K'	);
INSERT INTO Professor VALUES (	'Rezvani A'	);
INSERT INTO Professor VALUES (	'Blackshear J'	);
INSERT INTO Professor VALUES (	'Mark Leary'	);
INSERT INTO Professor VALUES (	'Steven Arsher'	);
INSERT INTO Professor VALUES (	'Grimes'	);
INSERT INTO Professor VALUES (	'Prillaman A'	);
INSERT INTO Professor VALUES (	'Marsh E'	);
INSERT INTO Professor VALUES (	'Brian Hare'	);
INSERT INTO Professor VALUES (	'Huttel S'	);
INSERT INTO Professor VALUES (	'Scott A Huettel and Jesse Summers'	);
INSERT INTO Professor VALUES (	'Puffer E'	);
INSERT INTO Professor VALUES (	'Maxson P'	);
INSERT INTO Professor VALUES (	'Jorgianne Robison'	);
INSERT INTO Professor VALUES (	'Shepherd S'	);
INSERT INTO Professor VALUES (	'Shepherd Steven'	);
INSERT INTO Professor VALUES (	'Gerend P'	);
INSERT INTO Professor VALUES (	'Moria J Smoski'	);
INSERT INTO Professor VALUES (	'Angela Vieth'	);
INSERT INTO Professor VALUES (	'Germain C'	);
INSERT INTO Professor VALUES (	'Zach Rosenthal'	);
INSERT INTO Professor VALUES (	'Zachery Mark Rosenthal'	);
INSERT INTO Professor VALUES (	'Gaither S'	);
INSERT INTO Professor VALUES (	'Bauer M'	);
INSERT INTO Professor VALUES (	'Robert Thompson'	);
INSERT INTO Professor VALUES (	'David Rubin'	);
INSERT INTO Professor VALUES (	'Tomasello M'	);
INSERT INTO Professor VALUES (	'Gaither'	);
INSERT INTO Professor VALUES (	'Mark Zachary Rosenthal '	);
INSERT INTO Professor VALUES (	'Gregory SL'	);
INSERT INTO Professor VALUES (	'Wilson A, Williams C'	);
INSERT INTO Professor VALUES (	'Bridgette Hard'	);
INSERT INTO Professor VALUES (	'Ruth Day'	);
INSERT INTO Professor VALUES (	'DIRK PHILIPSEN'	);
INSERT INTO Professor VALUES (	'Peck G'	);
INSERT INTO Professor VALUES (	'Annanat '	);
INSERT INTO Professor VALUES (	'Kristin G'	);
INSERT INTO Professor VALUES (	'Barn'	);
INSERT INTO Professor VALUES (	'F. Meyer'	);
INSERT INTO Professor VALUES (	'Bermeo S'	);
INSERT INTO Professor VALUES (	'Federick Mayer'	);
INSERT INTO Professor VALUES (	'Fredrick Mayer '	);
INSERT INTO Professor VALUES (	'Mayer F'	);
INSERT INTO Professor VALUES (	'Sarah Bermeo'	);
INSERT INTO Professor VALUES (	'Vigdor, Elizabeth'	);
INSERT INTO Professor VALUES (	'Barnes C'	);
INSERT INTO Professor VALUES (	'Taylor D'	);
INSERT INTO Professor VALUES (	'Byerly I'	);
INSERT INTO Professor VALUES (	'Tony Brown'	);
INSERT INTO Professor VALUES (	'Edna Andrew '	);
INSERT INTO Professor VALUES (	'Michael Newcity and Edna Andrews'	);
INSERT INTO Professor VALUES (	'Alma Blount'	);
INSERT INTO Professor VALUES (	'Brands H'	);
INSERT INTO Professor VALUES (	'Hollowell, A'	);
INSERT INTO Professor VALUES (	'A. Hollowell'	);
INSERT INTO Professor VALUES (	'Duara J'	);
INSERT INTO Professor VALUES (	'Starobin S'	);
INSERT INTO Professor VALUES (	'Sarah Bermeo '	);
INSERT INTO Professor VALUES (	'Goss K'	);
INSERT INTO Professor VALUES (	'Philp Napoli '	);
INSERT INTO Professor VALUES (	'Rose, Deondra'	);
INSERT INTO Professor VALUES (	'Rogerson K, Carnes N'	);
INSERT INTO Professor VALUES (	'A. Krishna'	);
INSERT INTO Professor VALUES (	'Carnes N'	);
INSERT INTO Professor VALUES (	'Jentleson B; Carnes N'	);
INSERT INTO Professor VALUES (	'Nicholas Carnes'	);
INSERT INTO Professor VALUES (	'Charney E'	);
INSERT INTO Professor VALUES (	'Pearson J'	);
INSERT INTO Professor VALUES (	'Evan Charney'	);
INSERT INTO Professor VALUES (	'Pfaff Talikoff A'	);
INSERT INTO Professor VALUES (	'Seth Sanders '	);
INSERT INTO Professor VALUES (	'Coffey'	);
INSERT INTO Professor VALUES (	'Sandeep Bhattacharya'	);
INSERT INTO Professor VALUES (	'Florence XXXX'	);
INSERT INTO Professor VALUES (	'Philips Bennett'	);
INSERT INTO Professor VALUES (	' Kipervaser A'	);
INSERT INTO Professor VALUES (	'Ed Timberlake'	);
INSERT INTO Professor VALUES (	'Deondra Rose'	);
INSERT INTO Professor VALUES (	'Rogerson K'	);
INSERT INTO Professor VALUES (	'Rogerson Kenneth'	);
INSERT INTO Professor VALUES (	'Fernando fernholz'	);
INSERT INTO Professor VALUES (	'Mayer, F'	);
INSERT INTO Professor VALUES (	'Kristen Goss'	);
INSERT INTO Professor VALUES (	'Amar Hamoudi'	);
INSERT INTO Professor VALUES (	'Sanders Bhattacharya '	);
INSERT INTO Professor VALUES (	'Suzanne Katzenstein'	);
INSERT INTO Professor VALUES (	'Kim Hwansoo'	);
INSERT INTO Professor VALUES (	'Joanne Van Tuyl'	);
INSERT INTO Professor VALUES (	'Chris Balis'	);
INSERT INTO Professor VALUES (	'Rebecca Bach'	);
INSERT INTO Professor VALUES (	'Gao Bai'	);
INSERT INTO Professor VALUES (	'Gao B'	);
INSERT INTO Professor VALUES (	'Hovespain M'	);
INSERT INTO Professor VALUES (	'Keister L'	);
INSERT INTO Professor VALUES (	'Keister L / Aronson'	);
INSERT INTO Professor VALUES (	'Rosenthal J'	);
INSERT INTO Professor VALUES (	'Mary Hovespian'	);
INSERT INTO Professor VALUES (	'Hamil J'	);
INSERT INTO Professor VALUES (	'Gold D'	);
INSERT INTO Professor VALUES (	'Tyson Brown'	);
INSERT INTO Professor VALUES (	'Suhey A'	);
INSERT INTO Professor VALUES (	'Fernandez Gonzalez A'	);
INSERT INTO Professor VALUES (	'Ibanez'	);
INSERT INTO Professor VALUES (	'Rosa Ibanez'	);
INSERT INTO Professor VALUES (	'A. Coefman'	);
INSERT INTO Professor VALUES (	'Lisa Merschel'	);
INSERT INTO Professor VALUES (	'Karahalios H'	);
INSERT INTO Professor VALUES (	'David Banks'	);
INSERT INTO Professor VALUES (	'Jerry Reiter'	);
INSERT INTO Professor VALUES (	'Reiter J'	);
INSERT INTO Professor VALUES (	'Cheng L'	);
INSERT INTO Professor VALUES (	'Junge M`'	);
INSERT INTO Professor VALUES (	'Li Cheng'	);
INSERT INTO Professor VALUES (	'Wu H'	);
INSERT INTO Professor VALUES (	'Li Ma'	);
INSERT INTO Professor VALUES (	'Li M'	);
INSERT INTO Professor VALUES (	'Reiter'	);
INSERT INTO Professor VALUES (	'Colin Rundel'	);
INSERT INTO Professor VALUES (	'Berger J'	);
INSERT INTO Professor VALUES (	'Jim Berger'	);
INSERT INTO Professor VALUES (	'Beka Steorts'	);
INSERT INTO Professor VALUES (	'Rebecca Steorts'	);
INSERT INTO Professor VALUES (	'Steorts'	);
INSERT INTO Professor VALUES (	'Collin Rundel'	);
INSERT INTO Professor VALUES (	'DeYoreo M'	);
INSERT INTO Professor VALUES (	'Mukherjee S'	);
INSERT INTO Professor VALUES (	'Sayan M'	);
INSERT INTO Professor VALUES (	'Amy Herring'	);
INSERT INTO Professor VALUES (	'Dunson D'	);
INSERT INTO Professor VALUES (	'Iversen'	);
INSERT INTO Professor VALUES (	'Merlise Clyde'	);
INSERT INTO Professor VALUES (	'Hoff P'	);
INSERT INTO Professor VALUES (	'Katherine Heller'	);
INSERT INTO Professor VALUES (	'Durrett R '	);
INSERT INTO Professor VALUES (	'Cliburn Chan'	);
INSERT INTO Professor VALUES (	'Rundel M'	);
INSERT INTO Professor VALUES (	'Anthea Monod'	);
INSERT INTO Professor VALUES (	'Morgan K'	);
INSERT INTO Professor VALUES (	'Abrahamsen T'	);
INSERT INTO Professor VALUES (	'Banks D'	);
INSERT INTO Professor VALUES (	'PhD Student'	);
INSERT INTO Professor VALUES (	'Rundel'	);
INSERT INTO Professor VALUES (	'Mine Centikaya Rundel'	);
INSERT INTO Professor VALUES (	'Dalene Stangl'	);
INSERT INTO Professor VALUES (	'Stangl D'	);
INSERT INTO Professor VALUES (	'Taylor-Rodriguez D'	);
INSERT INTO Professor VALUES (	'Basak A.'	);
INSERT INTO Professor VALUES (	'Durrett'	);
INSERT INTO Professor VALUES (	'Rundle C'	);
INSERT INTO Professor VALUES (	'David Bank'	);
INSERT INTO Professor VALUES (	'David Jones'	);
INSERT INTO Professor VALUES (	'Gelfand A'	);
INSERT INTO Professor VALUES (	'Ma L'	);
INSERT INTO Professor VALUES (	'Ma Li'	);
INSERT INTO Professor VALUES (	'Fan Li'	);
INSERT INTO Professor VALUES (	'Rundel C.'	);
INSERT INTO Professor VALUES (	'James Berger'	);
INSERT INTO Professor VALUES (	'David dunson'	);
INSERT INTO Professor VALUES (	'Mukherjee N'	);
INSERT INTO Professor VALUES (	'Jaeger A'	);
INSERT INTO Professor VALUES (	'Volfovsky A'	);
INSERT INTO Professor VALUES (	'Nabanita Mukherjee'	);
INSERT INTO Professor VALUES (	'Daniel Stangl'	);
INSERT INTO Professor VALUES (	'Maria Tackett'	);
INSERT INTO Professor VALUES (	'Marina Tackett'	);
INSERT INTO Professor VALUES (	'Alex Young'	);
INSERT INTO Professor VALUES (	'Durrett R'	);
INSERT INTO Professor VALUES (	'Greg Malen.'	);
INSERT INTO Professor VALUES (	'Gugan'	);
INSERT INTO Professor VALUES (	'Gugan Toppel'	);
INSERT INTO Professor VALUES (	'Ma Ruibo'	);
INSERT INTO Professor VALUES (	'Thorppe G'	);
INSERT INTO Professor VALUES (	'Wu'	);
INSERT INTO Professor VALUES (	'Jason Xu'	);
INSERT INTO Professor VALUES (	'Jones D'	);
INSERT INTO Professor VALUES (	'Maria Tackette'	);
INSERT INTO Professor VALUES (	'Klein, T'	);
INSERT INTO Professor VALUES (	'ROGERS'	);
INSERT INTO Professor VALUES (	'Madeline Lambert'	);
INSERT INTO Professor VALUES (	'Storer, Jeff'	);
INSERT INTO Professor VALUES (	'Rodgers'	);
INSERT INTO Professor VALUES (	'S Beckwith'	);
INSERT INTO Professor VALUES (	'Conceison C'	);
INSERT INTO Professor VALUES (	'E Hemphill'	);
INSERT INTO Professor VALUES (	'Torgovnick M, Malone M'	);
INSERT INTO Professor VALUES (	'BELL N'	);
INSERT INTO Professor VALUES (	'J Storer'	);
INSERT INTO Professor VALUES (	'Ellison D'	);
INSERT INTO Professor VALUES (	'Holmgren, Beth'	);
INSERT INTO Professor VALUES (	'Dana Marks'	);
INSERT INTO Professor VALUES (	'Tsetan'	);
INSERT INTO Professor VALUES (	'Szabo V'	);
INSERT INTO Professor VALUES (	'Szabo V.'	);
INSERT INTO Professor VALUES (	'Raquel Savetella de Prada'	);
INSERT INTO Professor VALUES (	'Katz J, Graham D'	);
INSERT INTO Professor VALUES (	'William Noland'	);
INSERT INTO Professor VALUES (	'Lanzoni K'	);
INSERT INTO Professor VALUES (	'Shannan H.'	);
INSERT INTO Professor VALUES (	'Rudy,Mary K'	);
INSERT INTO Professor VALUES (	'Rosenberg G'	);
INSERT INTO Professor VALUES (	'Rojas,Carlos'	);
INSERT INTO Professor VALUES (	'K. Lamm'	);
INSERT INTO Professor VALUES (	'Lisa Andres'	);
INSERT INTO Professor VALUES (	'Ennis M'	);
INSERT INTO Professor VALUES (	'Parks E'	);
INSERT INTO Professor VALUES (	'Smith L'	);
INSERT INTO Professor VALUES (	'Cary Moskovitz'	);
INSERT INTO Professor VALUES (	'Millar, K'	);
INSERT INTO Professor VALUES (	'Hanas E'	);
INSERT INTO Professor VALUES (	'Ahlquist D.'	);
INSERT INTO Professor VALUES (	'Watkins, B.'	);
INSERT INTO Professor VALUES (	'Pawlak L'	);
INSERT INTO Professor VALUES (	'Ennis, M'	);
INSERT INTO Professor VALUES (	'Dowland, S'	);
INSERT INTO Professor VALUES (	'Applebee A'	);
INSERT INTO Professor VALUES (	'M. Omelsky'	);
INSERT INTO Professor VALUES (	'Stephania Heim'	);
INSERT INTO Professor VALUES (	'Stephenia Heim'	);
INSERT INTO Professor VALUES (	'Lindsey Smith'	);
INSERT INTO Professor VALUES (	'Nganga Muchiri'	);
INSERT INTO Professor VALUES (	'Brenda Baletti'	);
INSERT INTO Professor VALUES (	'N. Eilbaum'	);
INSERT INTO Professor VALUES (	'Baletti '	);
INSERT INTO Professor VALUES (	'Baletti B'	);
INSERT INTO Professor VALUES (	'Amanda Pullum'	);
INSERT INTO Professor VALUES (	'Dr. Saiba Varma'	);
INSERT INTO Professor VALUES (	'Pihos P'	);
INSERT INTO Professor VALUES (	'Summers, J'	);
INSERT INTO Professor VALUES (	'Comer D'	);
INSERT INTO Professor VALUES (	'Jed Cohen'	);
INSERT INTO Professor VALUES (	'Aftab Jassal'	);
INSERT INTO Professor VALUES (	'Whitt M'	);
INSERT INTO Professor VALUES (	'Mathrew Whitt'	);
INSERT INTO Professor VALUES (	'Nicolas Eilbaum'	);
INSERT INTO Professor VALUES (	'Emma Graner'	);
INSERT INTO Professor VALUES (	'Spohrer'	);
INSERT INTO Professor VALUES (	'Sandra Sotelo-Miller'	);
INSERT INTO Professor VALUES (	'Adam Boyette'	);
INSERT INTO Professor VALUES (	'Davis, Joshua'	);
INSERT INTO Professor VALUES (	'Baletti'	);
INSERT INTO Professor VALUES (	'Jesse Summers'	);
INSERT INTO Professor VALUES (	'Jassal'	);
INSERT INTO Professor VALUES (	'Mark Ulet'	);
INSERT INTO Professor VALUES (	'Reilly L'	);
INSERT INTO Professor VALUES (	'Reilly, L'	);
INSERT INTO Professor VALUES (	'Reily L'	);
INSERT INTO Professor VALUES (	'Mara Kaufman'	);
INSERT INTO Professor VALUES (	'Font D'	);
INSERT INTO Professor VALUES (	'Kevin C'	);
INSERT INTO Professor VALUES (	'Kevin Casey'	);
INSERT INTO Professor VALUES (	'Peter Pihos'	);
INSERT INTO Professor VALUES (	'Joos Vincent'	);
INSERT INTO Professor VALUES (	'Kaufman M'	);
INSERT INTO Professor VALUES (	'S. Waldschimdt'	);
INSERT INTO Professor VALUES (	'Muchiri P'	);
INSERT INTO Professor VALUES (	'Amanda Pullum '	);
INSERT INTO Professor VALUES (	'Janine Rose'	);
INSERT INTO Professor VALUES (	'Bowles J'	);
INSERT INTO Professor VALUES (	'Ng'ang'a Muchiri'	);
INSERT INTO Professor VALUES (	'Gabriel Rosenberg'	);